import type { VerbDetails } from "../db/schema";
import type { VerbCategory, VerbConjugation } from "../types/greek-reference";

export const VERBS: Pick<
	VerbDetails,
	| "vocab_id"
	| "infinitive"
	| "conjugation_family"
	| "notes"
	| "present_ego"
	| "present_esy"
	| "present_aftos"
	| "present_emeis"
	| "present_eseis"
	| "present_aftoi"
	| "past_ego"
	| "past_esy"
	| "past_aftos"
	| "past_emeis"
	| "past_eseis"
	| "past_aftoi"
	| "future_ego"
	| "future_esy"
	| "future_aftos"
	| "future_emeis"
	| "future_eseis"
	| "future_aftoi"
>[] = [
	{
		vocab_id: 1,
		infinitive: "κάνω",
		conjugation_family: "Type A",
		notes: null,
		present_ego: "κάνω",
		present_esy: "κάνεις",
		present_aftos: "κάνει",
		present_emeis: "κάνουμε",
		present_eseis: "κάνετε",
		present_aftoi: "κάνουν",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 2,
		infinitive: "είμαι",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "είμαι",
		present_esy: "είσαι",
		present_aftos: "είναι",
		present_emeis: "είμαστε",
		present_eseis: "είστε",
		present_aftoi: "είναι",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 3,
		infinitive: "έχω",
		conjugation_family: "unknown",
		notes: null,
		present_ego: null,
		present_esy: null,
		present_aftos: null,
		present_emeis: null,
		present_eseis: null,
		present_aftoi: null,
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 4,
		infinitive: "έρχομαι",
		conjugation_family: "Type A",
		notes: null,
		present_ego: "έρχομαι",
		present_esy: "έρχεσαι",
		present_aftos: "έρχεται",
		present_emeis: "ερχόμαστε",
		present_eseis: "έρχεστε",
		present_aftoi: "έρχονται",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 5,
		infinitive: "θυμάμαι",
		conjugation_family: "Type B",
		notes: null,
		present_ego: "θυμάμαι",
		present_esy: "θυμάσαι",
		present_aftos: "θυμάται",
		present_emeis: "θυμόμαστε",
		present_eseis: "θυμάστε",
		present_aftoi: "θυμούνται",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 6,
		infinitive: "πάω",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "πάω",
		present_esy: "πας",
		present_aftos: "πάει",
		present_emeis: "πάμε",
		present_eseis: "πάτε",
		present_aftoi: "πάνε",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 7,
		infinitive: "λέω",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "λέω",
		present_esy: "λες",
		present_aftos: "λέει",
		present_emeis: "λέμε",
		present_eseis: "λέτε",
		present_aftoi: "λένε",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 8,
		infinitive: "τρώω",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "τρώω",
		present_esy: "τρώς",
		present_aftos: "τρώει",
		present_emeis: "τρώμε",
		present_eseis: "τρώτε",
		present_aftoi: "τρώνε",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
];

// VERB_CONJUGATIONS - Data structure expected by components
export const VERB_CONJUGATIONS: Record<string, VerbConjugation[]> = {
	kano: [
		{ person: "εγώ", form: "κάνω", highlighted: "-ω", english: "I do/make" },
		{ person: "εσύ", form: "κάνεις", highlighted: "-εις", english: "you do/make" },
		{ person: "αυτός/ή/ό", form: "κάνει", highlighted: "-ει", english: "he/she/it does/makes" },
		{ person: "εμείς", form: "κάνουμε", highlighted: "-ουμε", english: "we do/make" },
		{ person: "εσείς", form: "κάνετε", highlighted: "-ετε", english: "you (pl) do/make" },
		{ person: "αυτοί/ές/ά", form: "κάνουν", highlighted: "-ουν", english: "they do/make" },
	],
	milao: [
		{ person: "εγώ", form: "μιλάω", highlighted: "-άω", english: "I speak" },
		{ person: "εσύ", form: "μιλάς", highlighted: "-άς", english: "you speak" },
		{ person: "αυτός/ή/ό", form: "μιλάει", highlighted: "-άει", english: "he/she/it speaks" },
		{ person: "εμείς", form: "μιλάμε", highlighted: "-άμε", english: "we speak" },
		{ person: "εσείς", form: "μιλάτε", highlighted: "-άτε", english: "you (pl) speak" },
		{ person: "αυτοί/ές/ά", form: "μιλάνε", highlighted: "-άνε", english: "they speak" },
	],
	erhomai: [
		{ person: "εγώ", form: "έρχομαι", highlighted: "-ομαι", english: "I come" },
		{ person: "εσύ", form: "έρχεσαι", highlighted: "-εσαι", english: "you come" },
		{ person: "αυτός/ή/ό", form: "έρχεται", highlighted: "-εται", english: "he/she/it comes" },
		{ person: "εμείς", form: "ερχόμαστε", highlighted: "-όμαστε", english: "we come" },
		{ person: "εσείς", form: "έρχεστε", highlighted: "-εστε", english: "you (pl) come" },
		{ person: "αυτοί/ές/ά", form: "έρχονται", highlighted: "-ονται", english: "they come" },
	],
	thymamai: [
		{ person: "εγώ", form: "θυμάμαι", highlighted: "-άμαι", english: "I remember" },
		{ person: "εσύ", form: "θυμάσαι", highlighted: "-άσαι", english: "you remember" },
		{ person: "αυτός/ή/ό", form: "θυμάται", highlighted: "-άται", english: "he/she/it remembers" },
		{ person: "εμείς", form: "θυμόμαστε", highlighted: "-όμαστε", english: "we remember" },
		{ person: "εσείς", form: "θυμάστε", highlighted: "-άστε", english: "you (pl) remember" },
		{ person: "αυτοί/ές/ά", form: "θυμούνται", highlighted: "-ούνται", english: "they remember" },
	],
	pao: [
		{ person: "εγώ", form: "πάω", english: "I go" },
		{ person: "εσύ", form: "πας", english: "you go" },
		{ person: "αυτός/ή/ό", form: "πάει", english: "he/she/it goes" },
		{ person: "εμείς", form: "πάμε", english: "we go" },
		{ person: "εσείς", form: "πάτε", english: "you (pl) go" },
		{ person: "αυτοί/ές/ά", form: "πάνε", english: "they go" },
	],
	leo: [
		{ person: "εγώ", form: "λέω", english: "I say" },
		{ person: "εσύ", form: "λες", english: "you say" },
		{ person: "αυτός/ή/ό", form: "λέει", english: "he/she/it says" },
		{ person: "εμείς", form: "λέμε", english: "we say" },
		{ person: "εσείς", form: "λέτε", english: "you (pl) say" },
		{ person: "αυτοί/ές/ά", form: "λένε", english: "they say" },
	],
	troo: [
		{ person: "εγώ", form: "τρώω", english: "I eat" },
		{ person: "εσύ", form: "τρώς", english: "you eat" },
		{ person: "αυτός/ή/ό", form: "τρώει", english: "he/she/it eats" },
		{ person: "εμείς", form: "τρώμε", english: "we eat" },
		{ person: "εσείς", form: "τρώτε", english: "you (pl) eat" },
		{ person: "αυτοί/ές/ά", form: "τρώνε", english: "they eat" },
	],
	eimai: [
		{ person: "εγώ", form: "είμαι", english: "I am" },
		{ person: "εσύ", form: "είσαι", english: "you are" },
		{ person: "αυτός/ή/ό", form: "είναι", english: "he/she/it is" },
		{ person: "εμείς", form: "είμαστε", english: "we are" },
		{ person: "εσείς", form: "είστε", english: "you (pl) are" },
		{ person: "αυτοί/ές/ά", form: "είναι", english: "they are" },
	],
};

// VERB_CATEGORIES - Organized verb lists by pattern for the vocabulary page
export const VERB_CATEGORIES: VerbCategory[] = [
	{
		id: "v-active-type-a",
		title: "Active Verbs (-ω) - Type A: Stress on stem",
		verbs: [
			{ id: "v-kano", greek: "κάνω", english: "I do/make", pattern: "-ω family" },
			{ id: "v-echo", greek: "έχω", english: "I have", pattern: "-ω family" },
		],
	},
	{
		id: "v-active-type-b",
		title: "Active Verbs (-ω) - Type B: Stress on ending",
		verbs: [
			{ id: "v-milao", greek: "μιλάω", english: "I speak", pattern: "-άω/-ώ family" },
		],
	},
	{
		id: "v-passive-type-a",
		title: "Passive Verbs (-ομαι) - Type A: Stress on stem",
		verbs: [
			{ id: "v-erhomai", greek: "έρχομαι", english: "I come", pattern: "-ομαι family" },
		],
	},
	{
		id: "v-passive-type-b",
		title: "Passive Verbs (-ομαι) - Type B: Stress on ending",
		verbs: [
			{ id: "v-thymamai", greek: "θυμάμαι", english: "I remember", pattern: "-άμαι family" },
		],
	},
	{
		id: "v-irregular",
		title: "Irregular Verbs - Must Memorize",
		verbs: [
			{ id: "v-eimai", greek: "είμαι", english: "I am", pattern: "Irregular" },
			{ id: "v-pao", greek: "πάω", english: "I go", pattern: "Irregular" },
			{ id: "v-leo", greek: "λέω", english: "I say", pattern: "Irregular" },
			{ id: "v-troo", greek: "τρώω", english: "I eat", pattern: "Irregular" },
		],
	},
];

// Past and Future Tense Examples for Other Tenses page
export const PAST_TENSE_EXAMPLES: VerbConjugation[] = [
	{ person: "εγώ", form: "έκανα", english: "I did/made" },
	{ person: "εσύ", form: "έκανες", english: "you did/made" },
	{ person: "αυτός/ή/ό", form: "έκανε", english: "he/she/it did/made" },
	{ person: "εμείς", form: "κάναμε", english: "we did/made" },
	{ person: "εσείς", form: "κάνατε", english: "you (pl) did/made" },
	{ person: "αυτοί/ές/ά", form: "έκαναν", english: "they did/made" },
];

export const FUTURE_TENSE_EXAMPLES: VerbConjugation[] = [
	{ person: "εγώ", form: "θα κάνω", english: "I will do/make" },
	{ person: "εσύ", form: "θα κάνεις", english: "you will do/make" },
	{ person: "αυτός/ή/ό", form: "θα κάνει", english: "he/she/it will do/make" },
	{ person: "εμείς", form: "θα κάνουμε", english: "we will do/make" },
	{ person: "εσείς", form: "θα κάνετε", english: "you (pl) will do/make" },
	{ person: "αυτοί/ές/ά", form: "θα κάνουν", english: "they will do/make" },
];
