import type { VerbDetails } from "../db/schema";

export const VERBS: Pick<
	VerbDetails,
	| "vocab_id"
	| "infinitive"
	| "conjugation_family"
	| "notes"
	| "present_ego"
	| "present_esy"
	| "present_aftos"
	| "present_emeis"
	| "present_eseis"
	| "present_aftoi"
	| "past_ego"
	| "past_esy"
	| "past_aftos"
	| "past_emeis"
	| "past_eseis"
	| "past_aftoi"
	| "future_ego"
	| "future_esy"
	| "future_aftos"
	| "future_emeis"
	| "future_eseis"
	| "future_aftoi"
>[] = [
	{
		vocab_id: 1,
		infinitive: "κάνω",
		conjugation_family: "Type A",
		notes: null,
		present_ego: "κάνω",
		present_esy: "κάνεις",
		present_aftos: "κάνει",
		present_emeis: "κάνουμε",
		present_eseis: "κάνετε",
		present_aftoi: "κάνουν",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 2,
		infinitive: "είμαι",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "είμαι",
		present_esy: "είσαι",
		present_aftos: "είναι",
		present_emeis: "είμαστε",
		present_eseis: "είστε",
		present_aftoi: "είναι",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 3,
		infinitive: "έχω",
		conjugation_family: "unknown",
		notes: null,
		present_ego: null,
		present_esy: null,
		present_aftos: null,
		present_emeis: null,
		present_eseis: null,
		present_aftoi: null,
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 4,
		infinitive: "έρχομαι",
		conjugation_family: "Type A",
		notes: null,
		present_ego: "έρχομαι",
		present_esy: "έρχεσαι",
		present_aftos: "έρχεται",
		present_emeis: "ερχόμαστε",
		present_eseis: "έρχεστε",
		present_aftoi: "έρχονται",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 5,
		infinitive: "θυμάμαι",
		conjugation_family: "Type B",
		notes: null,
		present_ego: "θυμάμαι",
		present_esy: "θυμάσαι",
		present_aftos: "θυμάται",
		present_emeis: "θυμόμαστε",
		present_eseis: "θυμάστε",
		present_aftoi: "θυμούνται",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 6,
		infinitive: "πάω",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "πάω",
		present_esy: "πας",
		present_aftos: "πάει",
		present_emeis: "πάμε",
		present_eseis: "πάτε",
		present_aftoi: "πάνε",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 7,
		infinitive: "λέω",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "λέω",
		present_esy: "λες",
		present_aftos: "λέει",
		present_emeis: "λέμε",
		present_eseis: "λέτε",
		present_aftoi: "λένε",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
	{
		vocab_id: 8,
		infinitive: "τρώω",
		conjugation_family: "Irregular",
		notes: null,
		present_ego: "τρώω",
		present_esy: "τρώς",
		present_aftos: "τρώει",
		present_emeis: "τρώμε",
		present_eseis: "τρώτε",
		present_aftoi: "τρώνε",
		past_ego: null,
		past_esy: null,
		past_aftos: null,
		past_emeis: null,
		past_eseis: null,
		past_aftoi: null,
		future_ego: null,
		future_esy: null,
		future_aftos: null,
		future_emeis: null,
		future_eseis: null,
		future_aftoi: null,
	},
];
