import type { ConjugationFamily } from "@/lib/greek-grammar";
import type { CefrLevel } from "@/server/db/enums";

export interface VerbStem {
	lemma: string;
	aoristStem: string; // unaccented aorist/future consonant base passed to generateConjugations()
	family: ConjugationFamily;
	english: string;
	cefrLevel?: CefrLevel;
}

/**
 * Regular verb stems for auto-generated conjugations.
 *
 * Add any verb here (including lesson-file verbs) to have its full conjugation
 * set seeded automatically via generateConjugations(lemma, aoristStem, family).
 *
 * Irregular and -ομαι verbs stay in verb-conjugations.ts as hand-written entries.
 */
export const VERB_STEMS: VerbStem[] = [
	// ── Original core verbs ────────────────────────────────────────────────────
	{ lemma: "κάνω", aoristStem: "καν", family: "-ω", english: "I do/make", cefrLevel: "A1" },
	{ lemma: "μπορώ", aoristStem: "μπορεσ", family: "-άω/-ώ", english: "I can", cefrLevel: "A1" },
	{ lemma: "μιλάω", aoristStem: "μιλησ", family: "-άω/-ώ", english: "I speak", cefrLevel: "A1" },
	{ lemma: "αγαπάω", aoristStem: "αγαπησ", family: "-άω/-ώ", english: "I love", cefrLevel: "A2" },
	{ lemma: "δουλεύω", aoristStem: "δουλεψ", family: "-ω", english: "I work", cefrLevel: "A1" },
	{ lemma: "γράφω", aoristStem: "γραψ", family: "-ω", english: "I write", cefrLevel: "A2" },
	{ lemma: "διαβάζω", aoristStem: "διαβασ", family: "-ω", english: "I read", cefrLevel: "A1" },
	{ lemma: "μένω", aoristStem: "μειν", family: "-ω", english: "I stay/live", cefrLevel: "A1" },
	{ lemma: "ευχαριστώ", aoristStem: "ευχαριστησ", family: "-άω/-ώ", english: "I thank", cefrLevel: "A1" },
	{ lemma: "παρακαλώ", aoristStem: "παρακαλεσ", family: "-άω/-ώ", english: "I ask / please", cefrLevel: "A1" },
	{ lemma: "νομίζω", aoristStem: "νομισ", family: "-ω", english: "I think (opinion)", cefrLevel: "A1" },
	{ lemma: "λυπάμαι", aoristStem: "λυπ", family: "-άμαι", english: "I'm sorry", cefrLevel: "A2" },
	{ lemma: "φοβάμαι", aoristStem: "φοβ", family: "-άμαι", english: "I'm afraid", cefrLevel: "A1" },
	{ lemma: "πεθαίνω", aoristStem: "πεθαν", family: "-ω", english: "I die", cefrLevel: "B1" },

	// ── A1 verbs ───────────────────────────────────────────────────────────────
	{ lemma: "μισώ", aoristStem: "μισησ", family: "-άω/-ώ", english: "I hate", cefrLevel: "A1" },
	{
		lemma: "πεινάω",
		aoristStem: "πεινασ",
		family: "-άω/-ώ",
		english: "I am hungry",
		cefrLevel: "A1",
	},
	{ lemma: "ρωτάω", aoristStem: "ρωτησ", family: "-άω/-ώ", english: "I ask", cefrLevel: "A1" },
	{
		lemma: "περνάω",
		aoristStem: "περασ",
		family: "-άω/-ώ",
		english: "I pass/cross/have fun",
		cefrLevel: "A1",
	},
	{ lemma: "οδηγώ", aoristStem: "οδηγησ", family: "-άω/-ώ", english: "I drive", cefrLevel: "A1" },
	{
		lemma: "τηλεφωνώ",
		aoristStem: "τηλεφωνησ",
		family: "-άω/-ώ",
		english: "I phone/call",
		cefrLevel: "A1",
	},
	{ lemma: "γελάω", aoristStem: "γελασ", family: "-άω/-ώ", english: "I laugh", cefrLevel: "A1" },
	{
		lemma: "ξυπνάω",
		aoristStem: "ξυπνησ",
		family: "-άω/-ώ",
		english: "I wake up",
		cefrLevel: "A1",
	},
	{ lemma: "φιλάω", aoristStem: "φιλησ", family: "-άω/-ώ", english: "I kiss", cefrLevel: "A1" },
	{
		lemma: "κολυμπάω",
		aoristStem: "κολυμπησ",
		family: "-άω/-ώ",
		english: "I swim",
		cefrLevel: "A1",
	},
	{ lemma: "κοιμάμαι", aoristStem: "κοιμ", family: "-άμαι", english: "I sleep", cefrLevel: "A1" },
	{ lemma: "παίζω", aoristStem: "παιξ", family: "-ω", english: "I play", cefrLevel: "A1" },
	{ lemma: "φέρνω", aoristStem: "φερ", family: "-ω", english: "I bring", cefrLevel: "A1" },
	{
		lemma: "κλείνω",
		aoristStem: "κλεισ",
		family: "-ω",
		english: "I close/turn off/book",
		cefrLevel: "A1",
	},
	{
		lemma: "ανοίγω",
		aoristStem: "ανοιξ",
		family: "-ω",
		english: "I open/turn on",
		cefrLevel: "A1",
	},
	{ lemma: "τελειώνω", aoristStem: "τελειωσ", family: "-ω", english: "I finish", cefrLevel: "A1" },
	{ lemma: "χορεύω", aoristStem: "χορεψ", family: "-ω", english: "I dance", cefrLevel: "A1" },
	{ lemma: "μαγειρεύω", aoristStem: "μαγειρεψ", family: "-ω", english: "I cook", cefrLevel: "A1" },
	{ lemma: "κόβω", aoristStem: "κοψ", family: "-ω", english: "I cut", cefrLevel: "A1" },
	{ lemma: "ψωνίζω", aoristStem: "ψωνισ", family: "-ω", english: "I shop", cefrLevel: "A1" },
	{ lemma: "αρέσω", aoristStem: "αρεσ", family: "-ω", english: "I please", cefrLevel: "A1" },

	// ── A2 verbs ───────────────────────────────────────────────────────────────
	{ lemma: "περιμένω", aoristStem: "περιμεν", family: "-ω", english: "I wait", cefrLevel: "A2" },
	{
		lemma: "ψάχνω",
		aoristStem: "ψαξ",
		family: "-ω",
		english: "I search/look for",
		cefrLevel: "A2",
	},
	{ lemma: "αγοράζω", aoristStem: "αγορασ", family: "-ω", english: "I buy", cefrLevel: "A2" },
	{ lemma: "πληρώνω", aoristStem: "πληρωσ", family: "-ω", english: "I pay", cefrLevel: "A2" },
	{ lemma: "στέλνω", aoristStem: "στειλ", family: "-ω", english: "I send", cefrLevel: "A2" },
	{ lemma: "αρχίζω", aoristStem: "αρχισ", family: "-ω", english: "I start/begin", cefrLevel: "A2" },
	{
		lemma: "συνεχίζω",
		aoristStem: "συνεχισ",
		family: "-ω",
		english: "I continue",
		cefrLevel: "A2",
	},
	{ lemma: "ετοιμάζω", aoristStem: "ετοιμασ", family: "-ω", english: "I prepare", cefrLevel: "A2" },
	{ lemma: "ταξιδεύω", aoristStem: "ταξιδεψ", family: "-ω", english: "I travel", cefrLevel: "A2" },
	{ lemma: "γνωρίζω", aoristStem: "γνωρισ", family: "-ω", english: "I know/meet", cefrLevel: "A2" },
	{ lemma: "αλλάζω", aoristStem: "αλλαξ", family: "-ω", english: "I change", cefrLevel: "A2" },
	{ lemma: "χάνω", aoristStem: "χασ", family: "-ω", english: "I lose", cefrLevel: "A2" },
	{
		lemma: "αποφασίζω",
		aoristStem: "αποφασισ",
		family: "-ω",
		english: "I decide",
		cefrLevel: "A2",
	},
	{ lemma: "γυρίζω", aoristStem: "γυρισ", family: "-ω", english: "I return/turn", cefrLevel: "A2" },
	{
		lemma: "λείπω",
		aoristStem: "λειψ",
		family: "-ω",
		english: "I am missing/away",
		cefrLevel: "A2",
	},
	{ lemma: "κλέβω", aoristStem: "κλεψ", family: "-ω", english: "I steal", cefrLevel: "A2" },
	{ lemma: "πιστεύω", aoristStem: "πιστεψ", family: "-ω", english: "I believe", cefrLevel: "A2" },
	{
		lemma: "εννοώ",
		aoristStem: "εννοησ",
		family: "-άω/-ώ",
		english: "I mean/intend",
		cefrLevel: "A2",
	},
	{
		lemma: "προσπαθώ",
		aoristStem: "προσπαθησ",
		family: "-άω/-ώ",
		english: "I try",
		cefrLevel: "A2",
	},
	{ lemma: "εξηγώ", aoristStem: "εξηγησ", family: "-άω/-ώ", english: "I explain", cefrLevel: "A2" },
	{
		lemma: "καλώ",
		aoristStem: "καλεσ",
		family: "-άω/-ώ",
		english: "I call/invite",
		cefrLevel: "A2",
	},
	{ lemma: "βοηθάω", aoristStem: "βοηθησ", family: "-άω/-ώ", english: "I help", cefrLevel: "A2" },
	{
		lemma: "χαλάω",
		aoristStem: "χαλασ",
		family: "-άω/-ώ",
		english: "I break/spoil",
		cefrLevel: "A2",
	},
	{
		lemma: "τραγουδάω",
		aoristStem: "τραγουδησ",
		family: "-άω/-ώ",
		english: "I sing",
		cefrLevel: "A2",
	},
	{ lemma: "ξεχνάω", aoristStem: "ξεχασ", family: "-άω/-ώ", english: "I forget", cefrLevel: "A2" },
	{
		lemma: "συναντάω",
		aoristStem: "συναντησ",
		family: "-άω/-ώ",
		english: "I meet",
		cefrLevel: "A2",
	},
	{
		lemma: "ανησυχώ",
		aoristStem: "ανησυχησ",
		family: "-άω/-ώ",
		english: "I worry",
		cefrLevel: "A2",
	},
	{
		lemma: "χαμογελάω",
		aoristStem: "χαμογελασ",
		family: "-άω/-ώ",
		english: "I smile",
		cefrLevel: "A2",
	},
	{
		lemma: "κρατάω",
		aoristStem: "κρατησ",
		family: "-άω/-ώ",
		english: "I hold/keep",
		cefrLevel: "A2",
	},
	{
		lemma: "απαντάω",
		aoristStem: "απαντησ",
		family: "-άω/-ώ",
		english: "I answer",
		cefrLevel: "A2",
	},
	{ lemma: "θυμάμαι", aoristStem: "θυμ", family: "-άμαι", english: "I remember", cefrLevel: "A2" },

	// ── Paradigm audit — A1/A2 verbs that had no conjugation source ────────────
	{ lemma: "βάζω", aoristStem: "βαλ", family: "-ω", english: "I put", cefrLevel: "A1" },
	{
		lemma: "βγάζω",
		aoristStem: "βγαλ",
		family: "-ω",
		english: "I take off/take out",
		cefrLevel: "A2",
	},
	{ lemma: "σπουδάζω", aoristStem: "σπουδασ", family: "-ω", english: "I study", cefrLevel: "A1" },
	{
		lemma: "αφήνω",
		aoristStem: "αφησ",
		family: "-ω",
		english: "I let/leave behind",
		cefrLevel: "A2",
	},
	{ lemma: "ελπίζω", aoristStem: "ελπισ", family: "-ω", english: "I hope", cefrLevel: "A2" },
	{ lemma: "κερδίζω", aoristStem: "κερδισ", family: "-ω", english: "I win", cefrLevel: "A2" },
	{
		lemma: "πειράζω",
		aoristStem: "πειραξ",
		family: "-ω",
		english: "it bothers/matters",
		cefrLevel: "A2",
	},
	{ lemma: "τρέχω", aoristStem: "τρεξ", family: "-ω", english: "I run", cefrLevel: "A2" },
	{
		lemma: "προσέχω",
		aoristStem: "προσεξ",
		family: "-ω",
		english: "I pay attention/be careful",
		cefrLevel: "A2",
	},
	{ lemma: "φτάνω", aoristStem: "φτασ", family: "-ω", english: "I arrive", cefrLevel: "A2" },
	{ lemma: "φωνάζω", aoristStem: "φωναξ", family: "-ω", english: "I yell/shout", cefrLevel: "A2" },
	{
		lemma: "φωτογραφίζω",
		aoristStem: "φωτογραφισ",
		family: "-ω",
		english: "I photograph",
		cefrLevel: "A2",
	},
	{ lemma: "χαλαρώνω", aoristStem: "χαλαρωσ", family: "-ω", english: "I relax", cefrLevel: "A2" },
	{
		lemma: "διασκεδάζω",
		aoristStem: "διασκεδασ",
		family: "-ω",
		english: "I have fun",
		cefrLevel: "A2",
	},
	{
		lemma: "δοκιμάζω",
		aoristStem: "δοκιμασ",
		family: "-ω",
		english: "I try/taste",
		cefrLevel: "A2",
	},
	{ lemma: "διδάσκω", aoristStem: "διδαξ", family: "-ω", english: "I teach", cefrLevel: "A2" },
	{ lemma: "ζηλεύω", aoristStem: "ζηλεψ", family: "-ω", english: "I am jealous", cefrLevel: "A2" },
	{ lemma: "λύνω", aoristStem: "λυσ", family: "-ω", english: "I solve/resolve", cefrLevel: "A2" },
	{
		lemma: "μεγαλώνω",
		aoristStem: "μεγαλωσ",
		family: "-ω",
		english: "I grow up/grow",
		cefrLevel: "A2",
	},
	{ lemma: "μυρίζω", aoristStem: "μυρισ", family: "-ω", english: "I smell", cefrLevel: "A2" },
	{
		lemma: "ντύνω",
		aoristStem: "ντυσ",
		family: "-ω",
		english: "I dress (someone else)",
		cefrLevel: "A2",
	},
	{ lemma: "ξοδεύω", aoristStem: "ξοδεψ", family: "-ω", english: "I spend", cefrLevel: "A2" },
	// αγκαλιάζω, φτιάχνω, ταΐζω need hand-written entries: the generator counts
	// -ιά- as two syllables and skips the diaeresis, giving αγκαλίασα for αγκάλιασα.
	{ lemma: "ζητάω", aoristStem: "ζητησ", family: "-άω/-ώ", english: "I ask for", cefrLevel: "A2" },
	{
		lemma: "κοιτάω",
		aoristStem: "κοιταξ",
		family: "-άω/-ώ",
		english: "I look at/watch",
		cefrLevel: "A2",
	},
	{ lemma: "πουλάω", aoristStem: "πουλησ", family: "-άω/-ώ", english: "I sell", cefrLevel: "A2" },
	{ lemma: "φοράω", aoristStem: "φορεσ", family: "-άω/-ώ", english: "I wear", cefrLevel: "A2" },
	{
		lemma: "σταματάω",
		aoristStem: "σταματησ",
		family: "-άω/-ώ",
		english: "I stop",
		cefrLevel: "A2",
	},
	{ lemma: "συμφωνώ", aoristStem: "συμφωνησ", family: "-άω/-ώ", english: "I agree", cefrLevel: "A2" },
	{ lemma: "αργώ", aoristStem: "αργησ", family: "-άω/-ώ", english: "I am late", cefrLevel: "A2" },
];
