/**
 * One-time script to parse raw-freq-list.txt into a typed lookup.
 *
 * Source: opensubtitles.org Greek subtitle corpus (5000 most frequent words)
 * Run: node --import tsx scripts/parse-frequency-list.ts
 * Output: src/scripts/seed-data/frequency-lookup.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const INPUT = join(import.meta.dirname, "../raw-freq-list.txt");
const OUTPUT = join(import.meta.dirname, "../src/scripts/seed-data/frequency-lookup.ts");

const raw = readFileSync(INPUT, "utf-8");
const lines = raw.split("\n");

const lookup: Record<string, number> = {};
let rank = 0;

for (const line of lines) {
	const trimmed = line.trim();

	// Skip blank lines, the prose header, and section markers like "1-250"
	if (!trimmed || /^\d+-\d+$/.test(trimmed) || trimmed.startsWith("This is")) continue;

	// Each data line: "word frequency_count"
	const spaceIndex = trimmed.lastIndexOf(" ");
	if (spaceIndex === -1) continue;

	const word = trimmed.slice(0, spaceIndex).trim();
	const freqStr = trimmed.slice(spaceIndex + 1).trim();

	if (!word || !/^\d+$/.test(freqStr)) continue;

	rank++;
	lookup[word] = rank;
}

const entries = Object.entries(lookup)
	.sort((a, b) => a[1] - b[1])
	.map(([word, r]) => `\t"${word}": ${r},`)
	.join("\n");

const output = `// Auto-generated by scripts/parse-frequency-list.ts
// Source: opensubtitles.org Greek subtitle corpus — 5,000 most frequent words
// Key: Greek surface form. Value: frequency rank (1 = most frequent).
// Direct-match only — verb lemmas that differ from their most common inflected form will miss.
// Re-generate: node --import tsx scripts/parse-frequency-list.ts
export const GREEK_FREQUENCY_LOOKUP: Record<string, number> = {
${entries}
};
`;

writeFileSync(OUTPUT, output, "utf-8");
console.log(`Wrote ${rank} entries to ${OUTPUT}`);
