type Group = "nominal" | "pronouns" | "verbs" | "blocks";
type Mode = "type" | "paradigm" | "chunk";

export interface Drill {
	id: string;
	href: string;
	title: string;
	greek: string;
	english: string;
	group: Group;
	mode: Mode;
	minutes: number;
	phase?: string;
}

export const DRILLS: Drill[] = [
	// Nominal forms (articles, nouns, adjectives) — case-phased

	// DOER (nominative)
	{
		id: "articles-article-doer",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/articles/article-doer",
		title: "Article (Doer)",
		greek: "ο · η · το · οι · τα",
		english: "Articles in Doer form (sg + pl)",
		minutes: 1,
		phase: "Doer",
	},
	{
		id: "articles-noun-genders",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/articles/noun-genders",
		title: "Noun (Doer)",
		greek: "ο φίλος · η θάλασσα · το σπίτι",
		english: "Article + noun in Doer form, recognise gender",
		minutes: 1,
		phase: "Doer",
	},
	{
		id: "adjectives-agreement",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/adjectives/agreement",
		title: "Adjective (Doer)",
		greek: "καλός · καλή · καλό",
		english: "Three-form gender agreement",
		minutes: 2,
		phase: "Doer",
	},
	{
		id: "nominal-phrase-doer",
		group: "nominal",
		mode: "type",
		href: "/practice/nominal/phrase-doer",
		title: "Doer phrase",
		greek: "ο καλός φίλος · η μεγάλη πόλη · το νέο σπίτι",
		english: "Article + adjective + noun (Doer)",
		minutes: 2,
		phase: "Doer",
	},

	// TARGET (accusative)
	{
		id: "articles-article-target",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/articles/article-target",
		title: "Article (Target)",
		greek: "τον · τη · το · τους · τις · τα",
		english: "Articles in Target form (sg + pl)",
		minutes: 1,
		phase: "Target",
	},
	{
		id: "nominal-noun-target",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/articles/noun-target",
		title: "Noun (Target)",
		greek: "τον φίλο · τη μέρα · το σπίτι",
		english: "Article + noun in Target form",
		minutes: 1,
		phase: "Target",
	},
	{
		id: "adjectives-agreement-target",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/adjectives/agreement-target",
		title: "Adjective (Target)",
		greek: "καλό · καλή · καλό",
		english: "Three-form agreement, Target case",
		minutes: 2,
		phase: "Target",
	},
	{
		id: "nominal-phrase-target",
		group: "nominal",
		mode: "type",
		href: "/practice/nominal/phrase-target",
		title: "Target phrase",
		greek: "τον καλό φίλο · τη μεγάλη πόλη · το νέο σπίτι",
		english: "Article + adjective + noun (Target)",
		minutes: 2,
		phase: "Target",
	},

	// OWNER (genitive)
	{
		id: "articles-article-owner",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/articles/article-owner",
		title: "Article (Owner)",
		greek: "του · της · του · των",
		english: "Articles in Owner form (sg + pl)",
		minutes: 1,
		phase: "Owner",
	},
	{
		id: "nominal-noun-owner",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/articles/noun-owner",
		title: "Noun (Owner)",
		greek: "του φίλου · της μέρας · του σπιτιού",
		english: "Article + noun in Owner form",
		minutes: 1,
		phase: "Owner",
	},
	{
		id: "adjectives-agreement-owner",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/adjectives/agreement-owner",
		title: "Adjective (Owner)",
		greek: "καλού · καλής · καλού",
		english: "Three-form agreement, Owner case",
		minutes: 2,
		phase: "Owner",
	},
	{
		id: "nominal-phrase-owner",
		group: "nominal",
		mode: "type",
		href: "/practice/nominal/phrase-owner",
		title: "Owner phrase",
		greek: "του καλού φίλου · της μεγάλης πόλης · του νέου σπιτιού",
		english: "Article + adjective + noun (Owner)",
		minutes: 2,
		phase: "Owner",
	},

	// REVIEW (cross-case)
	{
		id: "articles-paradigm",
		group: "nominal",
		mode: "paradigm",
		href: "/practice/articles/paradigm",
		title: "All articles",
		greek: "ο, η, το, τον, την, του, της…",
		english: "All 18 forms — full paradigm grid",
		minutes: 1,
		phase: "Review",
	},
	{
		id: "nominal-all-nouns",
		group: "nominal",
		mode: "type",
		href: "/practice/nominal/all-nouns",
		title: "All nouns",
		greek: "φίλος · φίλο · φίλου · φίλοι · …",
		english: "Mixed cases across all nouns",
		minutes: 2,
		phase: "Review",
	},
	{
		id: "nominal-all-adjectives",
		group: "nominal",
		mode: "type",
		href: "/practice/nominal/all-adjectives",
		title: "All adjectives",
		greek: "καλός · καλή · καλό · καλού · καλής · …",
		english: "Mixed cases across all adjectives",
		minutes: 2,
		phase: "Review",
	},
	{
		id: "nominal-all-phrases",
		group: "nominal",
		mode: "type",
		href: "/practice/nominal/all-phrases",
		title: "All phrases",
		greek: "ο καλός φίλος · τη μεγάλη πόλη · του νέου σπιτιού",
		english: "Mixed-case review across all noun phrases",
		minutes: 2,
		phase: "Review",
	},

	// Pronouns
	{
		id: "pronouns-object",
		group: "pronouns",
		mode: "paradigm",
		href: "/practice/pronouns/object",
		title: "Object pronouns",
		greek: "με, σε, τον, την, μας, σας…",
		english: "Direct-object clitics",
		minutes: 1,
	},
	{
		id: "pronouns-placement",
		group: "pronouns",
		mode: "type",
		href: "/practice/pronouns/placement",
		title: "Placement",
		greek: "Με βλέπει · Δες με! · Θα με δει",
		english: "Where weak pronouns sit (pre-verb / imperative / particle)",
		minutes: 2,
	},
	{
		id: "pronouns-possessives",
		group: "pronouns",
		mode: "paradigm",
		href: "/practice/pronouns/possessives",
		title: "Possessives",
		greek: "μου, σου, του, της, μας…",
		english: "Possession enclitics",
		minutes: 1,
	},

	// Verbs
	{
		id: "verbs-present",
		group: "verbs",
		mode: "type",
		href: "/practice/verbs/present",
		title: "Basic verbs",
		greek: "λύω · θέλω · μπορώ",
		english: "Conjugate everyday verbs",
		minutes: 2,
		phase: "Present",
	},
	{
		id: "verbs-conjugation-endings",
		group: "verbs",
		mode: "paradigm",
		href: "/practice/verbs/conjugation-endings",
		title: "Conjugations",
		greek: "-ω · -εις · -ει · -ουμε · -ετε · -ουν",
		english: "Person endings across 6 paradigms",
		minutes: 1,
		phase: "Present",
	},
	{
		id: "verbs-present-irregular",
		group: "verbs",
		mode: "paradigm",
		href: "/practice/verbs/present-irregular",
		title: "Irregular verbs",
		greek: "έχω · πάω · λέω · τρώω · ακούω",
		english: "Irregular present-tense paradigms",
		minutes: 2,
		phase: "Present",
	},
	{
		id: "verbs-eimai-present",
		group: "verbs",
		mode: "paradigm",
		href: "/practice/verbs/eimai-present",
		title: "είμαι · present",
		greek: "είμαι · είσαι · είναι · είμαστε",
		english: 'Present forms of "to be" (irregular)',
		minutes: 1,
		phase: "Present",
	},
	{
		id: "verbs-aorist-conjugation",
		group: "verbs",
		mode: "type",
		href: "/practice/verbs/aorist-conjugation",
		title: "Conjugations",
		greek: "έκανα · έκανες · έκανε · κάναμε",
		english: "All 6 persons — past tense",
		minutes: 2,
		phase: "Past",
	},
	{
		id: "verbs-aorist-stems",
		group: "verbs",
		mode: "paradigm",
		href: "/practice/verbs/aorist-stems",
		title: "Irregular verbs",
		greek: "τρώω → έφαγα · πίνω → ήπια",
		english: "Irregular past-tense roots",
		minutes: 1,
		phase: "Past",
	},
	{
		id: "verbs-eimai-past",
		group: "verbs",
		mode: "paradigm",
		href: "/practice/verbs/eimai-past",
		title: "είμαι · past",
		greek: "ήμουν · ήσουν · ήταν · ήμασταν",
		english: 'Past forms of "to be" (irregular)',
		minutes: 1,
		phase: "Past",
	},
	{
		id: "verbs-aorist-formation",
		group: "verbs",
		mode: "paradigm",
		href: "/practice/verbs/aorist-formation",
		title: "Past ↔ present",
		greek: "γράφω → έγραψα · ανοίγω → άνοιξα",
		english: "Build past from present (and reverse)",
		minutes: 1,
		phase: "Past",
	},
	{
		id: "verbs-future-conjugation",
		group: "verbs",
		mode: "type",
		href: "/practice/verbs/future-conjugation",
		title: "Conjugations",
		greek: "θα γράψω · θα φάω · θα πάω",
		english: "All 6 persons — future tense",
		minutes: 2,
		phase: "Future",
	},
	{
		id: "verbs-na-constructions",
		group: "verbs",
		mode: "type",
		href: "/practice/verbs/na-constructions",
		title: "να-constructions",
		greek: "θέλω να φάω · πρέπει να πάω · μπορώ να έρθω",
		english: "Modal + να + verb (subjunctive)",
		minutes: 2,
		phase: "να-form",
	},
	{
		id: "verbs-imperatives",
		group: "verbs",
		mode: "paradigm",
		href: "/practice/verbs/imperatives",
		title: "Imperatives",
		greek: "Έλα! · Πες! · Δώσε! · Φέρε!",
		english: "Common command forms",
		minutes: 1,
		phase: "Commands",
	},

	// Building blocks
	{
		id: "blocks-chunks",
		group: "blocks",
		mode: "chunk",
		href: "/practice/blocks/chunks",
		title: "Survival phrases",
		greek: "Γεια σου · Ευχαριστώ · Θα ήθελα",
		english: "Whole phrases, no decomposition",
		minutes: 1,
	},
	{
		id: "blocks-numbers",
		group: "blocks",
		mode: "paradigm",
		href: "/practice/blocks/numbers",
		title: "Numbers",
		greek: "ένα, δύο, δέκα, είκοσι, τριάντα…",
		english: "1–100",
		minutes: 1,
	},
	{
		id: "blocks-days-of-week",
		group: "blocks",
		mode: "paradigm",
		href: "/practice/blocks/days-of-week",
		title: "Days & time",
		greek: "Δευτέρα · Τρίτη · χτες · αύριο",
		english: "Days, yesterday, tomorrow",
		minutes: 1,
	},
];

export const DRILL_BY_ID: Record<string, Drill> = Object.fromEntries(DRILLS.map((d) => [d.id, d]));

export const GROUP_META: Record<Group, { label: string }> = {
	nominal: { label: "The case system" },
	pronouns: { label: "Pronouns" },
	verbs: { label: "Verbs" },
	blocks: { label: "Building blocks" },
};
