/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiErrorsRouteImport } from "./routes/api/errors";
import { Route as ApiMilestonesRouteImport } from "./routes/api/milestones";
import { Route as ApiPushLogTapRouteImport } from "./routes/api/push/log-tap";
import { Route as ApiPushSnoozeRouteImport } from "./routes/api/push/snooze";
import { Route as ApiPushSubscribeRouteImport } from "./routes/api/push/subscribe";
import { Route as ApiPushUnsubscribeRouteImport } from "./routes/api/push/unsubscribe";
import { Route as ApiPushVapidKeyRouteImport } from "./routes/api/push/vapid-key";
import { Route as ApiWebauthnAuthOptionsRouteImport } from "./routes/api/webauthn/auth-options";
import { Route as ApiWebauthnAuthVerifyRouteImport } from "./routes/api/webauthn/auth-verify";
import { Route as ApiWebauthnRegisterOptionsRouteImport } from "./routes/api/webauthn/register-options";
import { Route as ApiWebauthnRegisterVerifyRouteImport } from "./routes/api/webauthn/register-verify";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LearnConversationsTabRouteImport } from "./routes/learn/conversations/$tab";
import { Route as LearnConversationsIndexRouteImport } from "./routes/learn/conversations/index";
import { Route as LearnEssentialsSubtabRouteImport } from "./routes/learn/essentials/$subtab";
import { Route as LearnEssentialsIndexRouteImport } from "./routes/learn/essentials/index";
import { Route as LearnIndexRouteImport } from "./routes/learn/index";
import { Route as LearnNounsRouteImport } from "./routes/learn/nouns";
import { Route as LearnPhrasesTabRouteImport } from "./routes/learn/phrases/$tab";
import { Route as LearnPhrasesIndexRouteImport } from "./routes/learn/phrases/index";
import { Route as LearnVerbsRouteImport } from "./routes/learn/verbs";
import { Route as LearnVerbsVerbIdRouteImport } from "./routes/learn/verbs/$verbId";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as PracticeLayoutRouteImport } from "./routes/practice/_layout";
import { Route as PracticeBlocksChunksRouteImport } from "./routes/practice/blocks/chunks";
import { Route as PracticeBlocksDaysOfWeekRouteImport } from "./routes/practice/blocks/days-of-week";
import { Route as PracticeBlocksIndexRouteImport } from "./routes/practice/blocks/index";
import { Route as PracticeBlocksNumbersRouteImport } from "./routes/practice/blocks/numbers";
import { Route as PracticeCasesAccusativeAdjectiveRouteImport } from "./routes/practice/cases/accusative/adjective";
import { Route as PracticeCasesAccusativeArticleRouteImport } from "./routes/practice/cases/accusative/article";
import { Route as PracticeCasesAccusativeNounRouteImport } from "./routes/practice/cases/accusative/noun";
import { Route as PracticeCasesAccusativePhraseRouteImport } from "./routes/practice/cases/accusative/phrase";
import { Route as PracticeCasesGenitiveAdjectiveRouteImport } from "./routes/practice/cases/genitive/adjective";
import { Route as PracticeCasesGenitiveArticleRouteImport } from "./routes/practice/cases/genitive/article";
import { Route as PracticeCasesGenitiveNounRouteImport } from "./routes/practice/cases/genitive/noun";
import { Route as PracticeCasesGenitivePhraseRouteImport } from "./routes/practice/cases/genitive/phrase";
import { Route as PracticeCasesIndexRouteImport } from "./routes/practice/cases/index";
import { Route as PracticeCasesNominativeAdjectiveRouteImport } from "./routes/practice/cases/nominative/adjective";
import { Route as PracticeCasesNominativeArticleRouteImport } from "./routes/practice/cases/nominative/article";
import { Route as PracticeCasesNominativeNounRouteImport } from "./routes/practice/cases/nominative/noun";
import { Route as PracticeCasesNominativePhraseRouteImport } from "./routes/practice/cases/nominative/phrase";
import { Route as PracticeCasesReviewAdjectivesRouteImport } from "./routes/practice/cases/review/adjectives";
import { Route as PracticeCasesReviewArticlesRouteImport } from "./routes/practice/cases/review/articles";
import { Route as PracticeCasesReviewNounsRouteImport } from "./routes/practice/cases/review/nouns";
import { Route as PracticeCasesReviewPhrasesRouteImport } from "./routes/practice/cases/review/phrases";
import { Route as PracticeIndexRouteImport } from "./routes/practice/index";
import { Route as PracticePronounsIndexRouteImport } from "./routes/practice/pronouns/index";
import { Route as PracticePronounsObjectRouteImport } from "./routes/practice/pronouns/object";
import { Route as PracticePronounsPlacementRouteImport } from "./routes/practice/pronouns/placement";
import { Route as PracticePronounsPossessivesRouteImport } from "./routes/practice/pronouns/possessives";
import { Route as PracticeVerbsConjugationEndingsRouteImport } from "./routes/practice/verbs/conjugation-endings";
import { Route as PracticeVerbsFutureConjugationRouteImport } from "./routes/practice/verbs/future-conjugation";
import { Route as PracticeVerbsImperativesRouteImport } from "./routes/practice/verbs/imperatives";
import { Route as PracticeVerbsIndexRouteImport } from "./routes/practice/verbs/index";
import { Route as PracticeVerbsNaConstructionsRouteImport } from "./routes/practice/verbs/na-constructions";
import { Route as PracticeVerbsPastAoristConjugationRouteImport } from "./routes/practice/verbs/past/aorist-conjugation";
import { Route as PracticeVerbsPastAoristFormationRouteImport } from "./routes/practice/verbs/past/aorist-formation";
import { Route as PracticeVerbsPastAoristStemsRouteImport } from "./routes/practice/verbs/past/aorist-stems";
import { Route as PracticeVerbsPastEimaiPastRouteImport } from "./routes/practice/verbs/past/eimai-past";
import { Route as PracticeVerbsPresentEimaiPresentRouteImport } from "./routes/practice/verbs/present/eimai-present";
import { Route as PracticeVerbsPresentPresentRouteImport } from "./routes/practice/verbs/present/present";
import { Route as PracticeVerbsPresentPresentIrregularRouteImport } from "./routes/practice/verbs/present/present-irregular";
import { Route as ProgressRouteImport } from "./routes/progress";
import { Route as ReferenceTabRouteImport } from "./routes/reference/$tab";
import { Route as ReferenceIndexRouteImport } from "./routes/reference/index";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as SupportRouteImport } from "./routes/support";
import { Route as TryRouteImport } from "./routes/try";

const TryRoute = TryRouteImport.update({
	id: "/try",
	path: "/try",
	getParentRoute: () => rootRouteImport,
} as any);
const SupportRoute = SupportRouteImport.update({
	id: "/support",
	path: "/support",
	getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
	id: "/search",
	path: "/search",
	getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
	id: "/register",
	path: "/register",
	getParentRoute: () => rootRouteImport,
} as any);
const ProgressRoute = ProgressRouteImport.update({
	id: "/progress",
	path: "/progress",
	getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
	id: "/login",
	path: "/login",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
	id: "/reference/",
	path: "/reference/",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeIndexRoute = PracticeIndexRouteImport.update({
	id: "/practice/",
	path: "/practice/",
	getParentRoute: () => rootRouteImport,
} as any);
const LearnIndexRoute = LearnIndexRouteImport.update({
	id: "/learn/",
	path: "/learn/",
	getParentRoute: () => rootRouteImport,
} as any);
const ReferenceTabRoute = ReferenceTabRouteImport.update({
	id: "/reference/$tab",
	path: "/reference/$tab",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeLayoutRoute = PracticeLayoutRouteImport.update({
	id: "/practice/_layout",
	path: "/practice",
	getParentRoute: () => rootRouteImport,
} as any);
const LearnVerbsRoute = LearnVerbsRouteImport.update({
	id: "/learn/verbs",
	path: "/learn/verbs",
	getParentRoute: () => rootRouteImport,
} as any);
const LearnNounsRoute = LearnNounsRouteImport.update({
	id: "/learn/nouns",
	path: "/learn/nouns",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiMilestonesRoute = ApiMilestonesRouteImport.update({
	id: "/api/milestones",
	path: "/api/milestones",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiErrorsRoute = ApiErrorsRouteImport.update({
	id: "/api/errors",
	path: "/api/errors",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsIndexRoute = PracticeVerbsIndexRouteImport.update({
	id: "/practice/verbs/",
	path: "/practice/verbs/",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticePronounsIndexRoute = PracticePronounsIndexRouteImport.update({
	id: "/practice/pronouns/",
	path: "/practice/pronouns/",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesIndexRoute = PracticeCasesIndexRouteImport.update({
	id: "/practice/cases/",
	path: "/practice/cases/",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeBlocksIndexRoute = PracticeBlocksIndexRouteImport.update({
	id: "/practice/blocks/",
	path: "/practice/blocks/",
	getParentRoute: () => rootRouteImport,
} as any);
const LearnPhrasesIndexRoute = LearnPhrasesIndexRouteImport.update({
	id: "/learn/phrases/",
	path: "/learn/phrases/",
	getParentRoute: () => rootRouteImport,
} as any);
const LearnEssentialsIndexRoute = LearnEssentialsIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => LearnEssentialsRouteRoute,
} as any);
const LearnConversationsIndexRoute = LearnConversationsIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => LearnConversationsRouteRoute,
} as any);
const PracticeVerbsNaConstructionsRoute = PracticeVerbsNaConstructionsRouteImport.update({
	id: "/practice/verbs/na-constructions",
	path: "/practice/verbs/na-constructions",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsImperativesRoute = PracticeVerbsImperativesRouteImport.update({
	id: "/practice/verbs/imperatives",
	path: "/practice/verbs/imperatives",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsFutureConjugationRoute = PracticeVerbsFutureConjugationRouteImport.update({
	id: "/practice/verbs/future-conjugation",
	path: "/practice/verbs/future-conjugation",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsConjugationEndingsRoute = PracticeVerbsConjugationEndingsRouteImport.update({
	id: "/practice/verbs/conjugation-endings",
	path: "/practice/verbs/conjugation-endings",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticePronounsPossessivesRoute = PracticePronounsPossessivesRouteImport.update({
	id: "/practice/pronouns/possessives",
	path: "/practice/pronouns/possessives",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticePronounsPlacementRoute = PracticePronounsPlacementRouteImport.update({
	id: "/practice/pronouns/placement",
	path: "/practice/pronouns/placement",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticePronounsObjectRoute = PracticePronounsObjectRouteImport.update({
	id: "/practice/pronouns/object",
	path: "/practice/pronouns/object",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeBlocksNumbersRoute = PracticeBlocksNumbersRouteImport.update({
	id: "/practice/blocks/numbers",
	path: "/practice/blocks/numbers",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeBlocksDaysOfWeekRoute = PracticeBlocksDaysOfWeekRouteImport.update({
	id: "/practice/blocks/days-of-week",
	path: "/practice/blocks/days-of-week",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeBlocksChunksRoute = PracticeBlocksChunksRouteImport.update({
	id: "/practice/blocks/chunks",
	path: "/practice/blocks/chunks",
	getParentRoute: () => rootRouteImport,
} as any);
const LearnVerbsVerbIdRoute = LearnVerbsVerbIdRouteImport.update({
	id: "/$verbId",
	path: "/$verbId",
	getParentRoute: () => LearnVerbsRoute,
} as any);
const LearnPhrasesTabRoute = LearnPhrasesTabRouteImport.update({
	id: "/learn/phrases/$tab",
	path: "/learn/phrases/$tab",
	getParentRoute: () => rootRouteImport,
} as any);
const LearnEssentialsSubtabRoute = LearnEssentialsSubtabRouteImport.update({
	id: "/$subtab",
	path: "/$subtab",
	getParentRoute: () => LearnEssentialsRouteRoute,
} as any);
const LearnConversationsTabRoute = LearnConversationsTabRouteImport.update({
	id: "/learn/conversations/$tab",
	path: "/learn/conversations/$tab",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiWebauthnRegisterVerifyRoute = ApiWebauthnRegisterVerifyRouteImport.update({
	id: "/api/webauthn/register-verify",
	path: "/api/webauthn/register-verify",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiWebauthnRegisterOptionsRoute = ApiWebauthnRegisterOptionsRouteImport.update({
	id: "/api/webauthn/register-options",
	path: "/api/webauthn/register-options",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiWebauthnAuthVerifyRoute = ApiWebauthnAuthVerifyRouteImport.update({
	id: "/api/webauthn/auth-verify",
	path: "/api/webauthn/auth-verify",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiWebauthnAuthOptionsRoute = ApiWebauthnAuthOptionsRouteImport.update({
	id: "/api/webauthn/auth-options",
	path: "/api/webauthn/auth-options",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPushVapidKeyRoute = ApiPushVapidKeyRouteImport.update({
	id: "/api/push/vapid-key",
	path: "/api/push/vapid-key",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
	id: "/api/push/unsubscribe",
	path: "/api/push/unsubscribe",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
	id: "/api/push/subscribe",
	path: "/api/push/subscribe",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPushSnoozeRoute = ApiPushSnoozeRouteImport.update({
	id: "/api/push/snooze",
	path: "/api/push/snooze",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPushLogTapRoute = ApiPushLogTapRouteImport.update({
	id: "/api/push/log-tap",
	path: "/api/push/log-tap",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsPresentPresentIrregularRoute =
	PracticeVerbsPresentPresentIrregularRouteImport.update({
		id: "/practice/verbs/present/present-irregular",
		path: "/practice/verbs/present/present-irregular",
		getParentRoute: () => rootRouteImport,
	} as any);
const PracticeVerbsPresentPresentRoute = PracticeVerbsPresentPresentRouteImport.update({
	id: "/practice/verbs/present/present",
	path: "/practice/verbs/present/present",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsPresentEimaiPresentRoute = PracticeVerbsPresentEimaiPresentRouteImport.update({
	id: "/practice/verbs/present/eimai-present",
	path: "/practice/verbs/present/eimai-present",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsPastEimaiPastRoute = PracticeVerbsPastEimaiPastRouteImport.update({
	id: "/practice/verbs/past/eimai-past",
	path: "/practice/verbs/past/eimai-past",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsPastAoristStemsRoute = PracticeVerbsPastAoristStemsRouteImport.update({
	id: "/practice/verbs/past/aorist-stems",
	path: "/practice/verbs/past/aorist-stems",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsPastAoristFormationRoute = PracticeVerbsPastAoristFormationRouteImport.update({
	id: "/practice/verbs/past/aorist-formation",
	path: "/practice/verbs/past/aorist-formation",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeVerbsPastAoristConjugationRoute =
	PracticeVerbsPastAoristConjugationRouteImport.update({
		id: "/practice/verbs/past/aorist-conjugation",
		path: "/practice/verbs/past/aorist-conjugation",
		getParentRoute: () => rootRouteImport,
	} as any);
const PracticeCasesReviewPhrasesRoute = PracticeCasesReviewPhrasesRouteImport.update({
	id: "/practice/cases/review/phrases",
	path: "/practice/cases/review/phrases",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesReviewNounsRoute = PracticeCasesReviewNounsRouteImport.update({
	id: "/practice/cases/review/nouns",
	path: "/practice/cases/review/nouns",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesReviewArticlesRoute = PracticeCasesReviewArticlesRouteImport.update({
	id: "/practice/cases/review/articles",
	path: "/practice/cases/review/articles",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesReviewAdjectivesRoute = PracticeCasesReviewAdjectivesRouteImport.update({
	id: "/practice/cases/review/adjectives",
	path: "/practice/cases/review/adjectives",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesNominativePhraseRoute = PracticeCasesNominativePhraseRouteImport.update({
	id: "/practice/cases/nominative/phrase",
	path: "/practice/cases/nominative/phrase",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesNominativeNounRoute = PracticeCasesNominativeNounRouteImport.update({
	id: "/practice/cases/nominative/noun",
	path: "/practice/cases/nominative/noun",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesNominativeArticleRoute = PracticeCasesNominativeArticleRouteImport.update({
	id: "/practice/cases/nominative/article",
	path: "/practice/cases/nominative/article",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesNominativeAdjectiveRoute = PracticeCasesNominativeAdjectiveRouteImport.update({
	id: "/practice/cases/nominative/adjective",
	path: "/practice/cases/nominative/adjective",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesGenitivePhraseRoute = PracticeCasesGenitivePhraseRouteImport.update({
	id: "/practice/cases/genitive/phrase",
	path: "/practice/cases/genitive/phrase",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesGenitiveNounRoute = PracticeCasesGenitiveNounRouteImport.update({
	id: "/practice/cases/genitive/noun",
	path: "/practice/cases/genitive/noun",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesGenitiveArticleRoute = PracticeCasesGenitiveArticleRouteImport.update({
	id: "/practice/cases/genitive/article",
	path: "/practice/cases/genitive/article",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesGenitiveAdjectiveRoute = PracticeCasesGenitiveAdjectiveRouteImport.update({
	id: "/practice/cases/genitive/adjective",
	path: "/practice/cases/genitive/adjective",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesAccusativePhraseRoute = PracticeCasesAccusativePhraseRouteImport.update({
	id: "/practice/cases/accusative/phrase",
	path: "/practice/cases/accusative/phrase",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesAccusativeNounRoute = PracticeCasesAccusativeNounRouteImport.update({
	id: "/practice/cases/accusative/noun",
	path: "/practice/cases/accusative/noun",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesAccusativeArticleRoute = PracticeCasesAccusativeArticleRouteImport.update({
	id: "/practice/cases/accusative/article",
	path: "/practice/cases/accusative/article",
	getParentRoute: () => rootRouteImport,
} as any);
const PracticeCasesAccusativeAdjectiveRoute = PracticeCasesAccusativeAdjectiveRouteImport.update({
	id: "/practice/cases/accusative/adjective",
	path: "/practice/cases/accusative/adjective",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/progress": typeof ProgressRoute;
	"/register": typeof RegisterRoute;
	"/search": typeof SearchRoute;
	"/support": typeof SupportRoute;
	"/try": typeof TryRoute;
	"/api/errors": typeof ApiErrorsRoute;
	"/api/milestones": typeof ApiMilestonesRoute;
	"/learn/nouns": typeof LearnNounsRoute;
	"/learn/verbs": typeof LearnVerbsRouteWithChildren;
	"/practice": typeof PracticeLayoutRoute;
	"/reference/$tab": typeof ReferenceTabRoute;
	"/learn/": typeof LearnIndexRoute;
	"/practice/": typeof PracticeIndexRoute;
	"/reference/": typeof ReferenceIndexRoute;
	"/api/push/log-tap": typeof ApiPushLogTapRoute;
	"/api/push/snooze": typeof ApiPushSnoozeRoute;
	"/api/push/subscribe": typeof ApiPushSubscribeRoute;
	"/api/push/unsubscribe": typeof ApiPushUnsubscribeRoute;
	"/api/push/vapid-key": typeof ApiPushVapidKeyRoute;
	"/api/webauthn/auth-options": typeof ApiWebauthnAuthOptionsRoute;
	"/api/webauthn/auth-verify": typeof ApiWebauthnAuthVerifyRoute;
	"/api/webauthn/register-options": typeof ApiWebauthnRegisterOptionsRoute;
	"/api/webauthn/register-verify": typeof ApiWebauthnRegisterVerifyRoute;
	"/learn/conversations/$tab": typeof LearnConversationsTabRoute;
	"/learn/essentials/$subtab": typeof LearnEssentialsSubtabRoute;
	"/learn/phrases/$tab": typeof LearnPhrasesTabRoute;
	"/learn/verbs/$verbId": typeof LearnVerbsVerbIdRoute;
	"/practice/blocks/chunks": typeof PracticeBlocksChunksRoute;
	"/practice/blocks/days-of-week": typeof PracticeBlocksDaysOfWeekRoute;
	"/practice/blocks/numbers": typeof PracticeBlocksNumbersRoute;
	"/practice/pronouns/object": typeof PracticePronounsObjectRoute;
	"/practice/pronouns/placement": typeof PracticePronounsPlacementRoute;
	"/practice/pronouns/possessives": typeof PracticePronounsPossessivesRoute;
	"/practice/verbs/conjugation-endings": typeof PracticeVerbsConjugationEndingsRoute;
	"/practice/verbs/future-conjugation": typeof PracticeVerbsFutureConjugationRoute;
	"/practice/verbs/imperatives": typeof PracticeVerbsImperativesRoute;
	"/practice/verbs/na-constructions": typeof PracticeVerbsNaConstructionsRoute;
	"/learn/conversations/": typeof LearnConversationsIndexRoute;
	"/learn/essentials/": typeof LearnEssentialsIndexRoute;
	"/learn/phrases/": typeof LearnPhrasesIndexRoute;
	"/practice/blocks/": typeof PracticeBlocksIndexRoute;
	"/practice/cases/": typeof PracticeCasesIndexRoute;
	"/practice/pronouns/": typeof PracticePronounsIndexRoute;
	"/practice/verbs/": typeof PracticeVerbsIndexRoute;
	"/practice/cases/accusative/adjective": typeof PracticeCasesAccusativeAdjectiveRoute;
	"/practice/cases/accusative/article": typeof PracticeCasesAccusativeArticleRoute;
	"/practice/cases/accusative/noun": typeof PracticeCasesAccusativeNounRoute;
	"/practice/cases/accusative/phrase": typeof PracticeCasesAccusativePhraseRoute;
	"/practice/cases/genitive/adjective": typeof PracticeCasesGenitiveAdjectiveRoute;
	"/practice/cases/genitive/article": typeof PracticeCasesGenitiveArticleRoute;
	"/practice/cases/genitive/noun": typeof PracticeCasesGenitiveNounRoute;
	"/practice/cases/genitive/phrase": typeof PracticeCasesGenitivePhraseRoute;
	"/practice/cases/nominative/adjective": typeof PracticeCasesNominativeAdjectiveRoute;
	"/practice/cases/nominative/article": typeof PracticeCasesNominativeArticleRoute;
	"/practice/cases/nominative/noun": typeof PracticeCasesNominativeNounRoute;
	"/practice/cases/nominative/phrase": typeof PracticeCasesNominativePhraseRoute;
	"/practice/cases/review/adjectives": typeof PracticeCasesReviewAdjectivesRoute;
	"/practice/cases/review/articles": typeof PracticeCasesReviewArticlesRoute;
	"/practice/cases/review/nouns": typeof PracticeCasesReviewNounsRoute;
	"/practice/cases/review/phrases": typeof PracticeCasesReviewPhrasesRoute;
	"/practice/verbs/past/aorist-conjugation": typeof PracticeVerbsPastAoristConjugationRoute;
	"/practice/verbs/past/aorist-formation": typeof PracticeVerbsPastAoristFormationRoute;
	"/practice/verbs/past/aorist-stems": typeof PracticeVerbsPastAoristStemsRoute;
	"/practice/verbs/past/eimai-past": typeof PracticeVerbsPastEimaiPastRoute;
	"/practice/verbs/present/eimai-present": typeof PracticeVerbsPresentEimaiPresentRoute;
	"/practice/verbs/present/present": typeof PracticeVerbsPresentPresentRoute;
	"/practice/verbs/present/present-irregular": typeof PracticeVerbsPresentPresentIrregularRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/progress": typeof ProgressRoute;
	"/register": typeof RegisterRoute;
	"/search": typeof SearchRoute;
	"/support": typeof SupportRoute;
	"/try": typeof TryRoute;
	"/api/errors": typeof ApiErrorsRoute;
	"/api/milestones": typeof ApiMilestonesRoute;
	"/learn/nouns": typeof LearnNounsRoute;
	"/learn/verbs": typeof LearnVerbsRouteWithChildren;
	"/practice": typeof PracticeIndexRoute;
	"/reference/$tab": typeof ReferenceTabRoute;
	"/learn": typeof LearnIndexRoute;
	"/reference": typeof ReferenceIndexRoute;
	"/api/push/log-tap": typeof ApiPushLogTapRoute;
	"/api/push/snooze": typeof ApiPushSnoozeRoute;
	"/api/push/subscribe": typeof ApiPushSubscribeRoute;
	"/api/push/unsubscribe": typeof ApiPushUnsubscribeRoute;
	"/api/push/vapid-key": typeof ApiPushVapidKeyRoute;
	"/api/webauthn/auth-options": typeof ApiWebauthnAuthOptionsRoute;
	"/api/webauthn/auth-verify": typeof ApiWebauthnAuthVerifyRoute;
	"/api/webauthn/register-options": typeof ApiWebauthnRegisterOptionsRoute;
	"/api/webauthn/register-verify": typeof ApiWebauthnRegisterVerifyRoute;
	"/learn/conversations/$tab": typeof LearnConversationsTabRoute;
	"/learn/essentials/$subtab": typeof LearnEssentialsSubtabRoute;
	"/learn/phrases/$tab": typeof LearnPhrasesTabRoute;
	"/learn/verbs/$verbId": typeof LearnVerbsVerbIdRoute;
	"/practice/blocks/chunks": typeof PracticeBlocksChunksRoute;
	"/practice/blocks/days-of-week": typeof PracticeBlocksDaysOfWeekRoute;
	"/practice/blocks/numbers": typeof PracticeBlocksNumbersRoute;
	"/practice/pronouns/object": typeof PracticePronounsObjectRoute;
	"/practice/pronouns/placement": typeof PracticePronounsPlacementRoute;
	"/practice/pronouns/possessives": typeof PracticePronounsPossessivesRoute;
	"/practice/verbs/conjugation-endings": typeof PracticeVerbsConjugationEndingsRoute;
	"/practice/verbs/future-conjugation": typeof PracticeVerbsFutureConjugationRoute;
	"/practice/verbs/imperatives": typeof PracticeVerbsImperativesRoute;
	"/practice/verbs/na-constructions": typeof PracticeVerbsNaConstructionsRoute;
	"/learn/conversations": typeof LearnConversationsIndexRoute;
	"/learn/essentials": typeof LearnEssentialsIndexRoute;
	"/learn/phrases": typeof LearnPhrasesIndexRoute;
	"/practice/blocks": typeof PracticeBlocksIndexRoute;
	"/practice/cases": typeof PracticeCasesIndexRoute;
	"/practice/pronouns": typeof PracticePronounsIndexRoute;
	"/practice/verbs": typeof PracticeVerbsIndexRoute;
	"/practice/cases/accusative/adjective": typeof PracticeCasesAccusativeAdjectiveRoute;
	"/practice/cases/accusative/article": typeof PracticeCasesAccusativeArticleRoute;
	"/practice/cases/accusative/noun": typeof PracticeCasesAccusativeNounRoute;
	"/practice/cases/accusative/phrase": typeof PracticeCasesAccusativePhraseRoute;
	"/practice/cases/genitive/adjective": typeof PracticeCasesGenitiveAdjectiveRoute;
	"/practice/cases/genitive/article": typeof PracticeCasesGenitiveArticleRoute;
	"/practice/cases/genitive/noun": typeof PracticeCasesGenitiveNounRoute;
	"/practice/cases/genitive/phrase": typeof PracticeCasesGenitivePhraseRoute;
	"/practice/cases/nominative/adjective": typeof PracticeCasesNominativeAdjectiveRoute;
	"/practice/cases/nominative/article": typeof PracticeCasesNominativeArticleRoute;
	"/practice/cases/nominative/noun": typeof PracticeCasesNominativeNounRoute;
	"/practice/cases/nominative/phrase": typeof PracticeCasesNominativePhraseRoute;
	"/practice/cases/review/adjectives": typeof PracticeCasesReviewAdjectivesRoute;
	"/practice/cases/review/articles": typeof PracticeCasesReviewArticlesRoute;
	"/practice/cases/review/nouns": typeof PracticeCasesReviewNounsRoute;
	"/practice/cases/review/phrases": typeof PracticeCasesReviewPhrasesRoute;
	"/practice/verbs/past/aorist-conjugation": typeof PracticeVerbsPastAoristConjugationRoute;
	"/practice/verbs/past/aorist-formation": typeof PracticeVerbsPastAoristFormationRoute;
	"/practice/verbs/past/aorist-stems": typeof PracticeVerbsPastAoristStemsRoute;
	"/practice/verbs/past/eimai-past": typeof PracticeVerbsPastEimaiPastRoute;
	"/practice/verbs/present/eimai-present": typeof PracticeVerbsPresentEimaiPresentRoute;
	"/practice/verbs/present/present": typeof PracticeVerbsPresentPresentRoute;
	"/practice/verbs/present/present-irregular": typeof PracticeVerbsPresentPresentIrregularRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/progress": typeof ProgressRoute;
	"/register": typeof RegisterRoute;
	"/search": typeof SearchRoute;
	"/support": typeof SupportRoute;
	"/try": typeof TryRoute;
	"/api/errors": typeof ApiErrorsRoute;
	"/api/milestones": typeof ApiMilestonesRoute;
	"/learn/nouns": typeof LearnNounsRoute;
	"/learn/verbs": typeof LearnVerbsRouteWithChildren;
	"/practice/_layout": typeof PracticeLayoutRoute;
	"/reference/$tab": typeof ReferenceTabRoute;
	"/learn/": typeof LearnIndexRoute;
	"/practice/": typeof PracticeIndexRoute;
	"/reference/": typeof ReferenceIndexRoute;
	"/api/push/log-tap": typeof ApiPushLogTapRoute;
	"/api/push/snooze": typeof ApiPushSnoozeRoute;
	"/api/push/subscribe": typeof ApiPushSubscribeRoute;
	"/api/push/unsubscribe": typeof ApiPushUnsubscribeRoute;
	"/api/push/vapid-key": typeof ApiPushVapidKeyRoute;
	"/api/webauthn/auth-options": typeof ApiWebauthnAuthOptionsRoute;
	"/api/webauthn/auth-verify": typeof ApiWebauthnAuthVerifyRoute;
	"/api/webauthn/register-options": typeof ApiWebauthnRegisterOptionsRoute;
	"/api/webauthn/register-verify": typeof ApiWebauthnRegisterVerifyRoute;
	"/learn/conversations/$tab": typeof LearnConversationsTabRoute;
	"/learn/essentials/$subtab": typeof LearnEssentialsSubtabRoute;
	"/learn/phrases/$tab": typeof LearnPhrasesTabRoute;
	"/learn/verbs/$verbId": typeof LearnVerbsVerbIdRoute;
	"/practice/blocks/chunks": typeof PracticeBlocksChunksRoute;
	"/practice/blocks/days-of-week": typeof PracticeBlocksDaysOfWeekRoute;
	"/practice/blocks/numbers": typeof PracticeBlocksNumbersRoute;
	"/practice/pronouns/object": typeof PracticePronounsObjectRoute;
	"/practice/pronouns/placement": typeof PracticePronounsPlacementRoute;
	"/practice/pronouns/possessives": typeof PracticePronounsPossessivesRoute;
	"/practice/verbs/conjugation-endings": typeof PracticeVerbsConjugationEndingsRoute;
	"/practice/verbs/future-conjugation": typeof PracticeVerbsFutureConjugationRoute;
	"/practice/verbs/imperatives": typeof PracticeVerbsImperativesRoute;
	"/practice/verbs/na-constructions": typeof PracticeVerbsNaConstructionsRoute;
	"/learn/conversations/": typeof LearnConversationsIndexRoute;
	"/learn/essentials/": typeof LearnEssentialsIndexRoute;
	"/learn/phrases/": typeof LearnPhrasesIndexRoute;
	"/practice/blocks/": typeof PracticeBlocksIndexRoute;
	"/practice/cases/": typeof PracticeCasesIndexRoute;
	"/practice/pronouns/": typeof PracticePronounsIndexRoute;
	"/practice/verbs/": typeof PracticeVerbsIndexRoute;
	"/practice/cases/accusative/adjective": typeof PracticeCasesAccusativeAdjectiveRoute;
	"/practice/cases/accusative/article": typeof PracticeCasesAccusativeArticleRoute;
	"/practice/cases/accusative/noun": typeof PracticeCasesAccusativeNounRoute;
	"/practice/cases/accusative/phrase": typeof PracticeCasesAccusativePhraseRoute;
	"/practice/cases/genitive/adjective": typeof PracticeCasesGenitiveAdjectiveRoute;
	"/practice/cases/genitive/article": typeof PracticeCasesGenitiveArticleRoute;
	"/practice/cases/genitive/noun": typeof PracticeCasesGenitiveNounRoute;
	"/practice/cases/genitive/phrase": typeof PracticeCasesGenitivePhraseRoute;
	"/practice/cases/nominative/adjective": typeof PracticeCasesNominativeAdjectiveRoute;
	"/practice/cases/nominative/article": typeof PracticeCasesNominativeArticleRoute;
	"/practice/cases/nominative/noun": typeof PracticeCasesNominativeNounRoute;
	"/practice/cases/nominative/phrase": typeof PracticeCasesNominativePhraseRoute;
	"/practice/cases/review/adjectives": typeof PracticeCasesReviewAdjectivesRoute;
	"/practice/cases/review/articles": typeof PracticeCasesReviewArticlesRoute;
	"/practice/cases/review/nouns": typeof PracticeCasesReviewNounsRoute;
	"/practice/cases/review/phrases": typeof PracticeCasesReviewPhrasesRoute;
	"/practice/verbs/past/aorist-conjugation": typeof PracticeVerbsPastAoristConjugationRoute;
	"/practice/verbs/past/aorist-formation": typeof PracticeVerbsPastAoristFormationRoute;
	"/practice/verbs/past/aorist-stems": typeof PracticeVerbsPastAoristStemsRoute;
	"/practice/verbs/past/eimai-past": typeof PracticeVerbsPastEimaiPastRoute;
	"/practice/verbs/present/eimai-present": typeof PracticeVerbsPresentEimaiPresentRoute;
	"/practice/verbs/present/present": typeof PracticeVerbsPresentPresentRoute;
	"/practice/verbs/present/present-irregular": typeof PracticeVerbsPresentPresentIrregularRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/login"
		| "/progress"
		| "/register"
		| "/search"
		| "/support"
		| "/try"
		| "/api/errors"
		| "/api/milestones"
		| "/learn/nouns"
		| "/learn/verbs"
		| "/practice"
		| "/reference/$tab"
		| "/learn/"
		| "/practice/"
		| "/reference/"
		| "/api/push/log-tap"
		| "/api/push/snooze"
		| "/api/push/subscribe"
		| "/api/push/unsubscribe"
		| "/api/push/vapid-key"
		| "/api/webauthn/auth-options"
		| "/api/webauthn/auth-verify"
		| "/api/webauthn/register-options"
		| "/api/webauthn/register-verify"
		| "/learn/conversations/$tab"
		| "/learn/essentials/$subtab"
		| "/learn/phrases/$tab"
		| "/learn/verbs/$verbId"
		| "/practice/blocks/chunks"
		| "/practice/blocks/days-of-week"
		| "/practice/blocks/numbers"
		| "/practice/pronouns/object"
		| "/practice/pronouns/placement"
		| "/practice/pronouns/possessives"
		| "/practice/verbs/conjugation-endings"
		| "/practice/verbs/future-conjugation"
		| "/practice/verbs/imperatives"
		| "/practice/verbs/na-constructions"
		| "/learn/conversations/"
		| "/learn/essentials/"
		| "/learn/phrases/"
		| "/practice/blocks/"
		| "/practice/cases/"
		| "/practice/pronouns/"
		| "/practice/verbs/"
		| "/practice/cases/accusative/adjective"
		| "/practice/cases/accusative/article"
		| "/practice/cases/accusative/noun"
		| "/practice/cases/accusative/phrase"
		| "/practice/cases/genitive/adjective"
		| "/practice/cases/genitive/article"
		| "/practice/cases/genitive/noun"
		| "/practice/cases/genitive/phrase"
		| "/practice/cases/nominative/adjective"
		| "/practice/cases/nominative/article"
		| "/practice/cases/nominative/noun"
		| "/practice/cases/nominative/phrase"
		| "/practice/cases/review/adjectives"
		| "/practice/cases/review/articles"
		| "/practice/cases/review/nouns"
		| "/practice/cases/review/phrases"
		| "/practice/verbs/past/aorist-conjugation"
		| "/practice/verbs/past/aorist-formation"
		| "/practice/verbs/past/aorist-stems"
		| "/practice/verbs/past/eimai-past"
		| "/practice/verbs/present/eimai-present"
		| "/practice/verbs/present/present"
		| "/practice/verbs/present/present-irregular";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/login"
		| "/progress"
		| "/register"
		| "/search"
		| "/support"
		| "/try"
		| "/api/errors"
		| "/api/milestones"
		| "/learn/nouns"
		| "/learn/verbs"
		| "/practice"
		| "/reference/$tab"
		| "/learn"
		| "/reference"
		| "/api/push/log-tap"
		| "/api/push/snooze"
		| "/api/push/subscribe"
		| "/api/push/unsubscribe"
		| "/api/push/vapid-key"
		| "/api/webauthn/auth-options"
		| "/api/webauthn/auth-verify"
		| "/api/webauthn/register-options"
		| "/api/webauthn/register-verify"
		| "/learn/conversations/$tab"
		| "/learn/essentials/$subtab"
		| "/learn/phrases/$tab"
		| "/learn/verbs/$verbId"
		| "/practice/blocks/chunks"
		| "/practice/blocks/days-of-week"
		| "/practice/blocks/numbers"
		| "/practice/pronouns/object"
		| "/practice/pronouns/placement"
		| "/practice/pronouns/possessives"
		| "/practice/verbs/conjugation-endings"
		| "/practice/verbs/future-conjugation"
		| "/practice/verbs/imperatives"
		| "/practice/verbs/na-constructions"
		| "/learn/conversations"
		| "/learn/essentials"
		| "/learn/phrases"
		| "/practice/blocks"
		| "/practice/cases"
		| "/practice/pronouns"
		| "/practice/verbs"
		| "/practice/cases/accusative/adjective"
		| "/practice/cases/accusative/article"
		| "/practice/cases/accusative/noun"
		| "/practice/cases/accusative/phrase"
		| "/practice/cases/genitive/adjective"
		| "/practice/cases/genitive/article"
		| "/practice/cases/genitive/noun"
		| "/practice/cases/genitive/phrase"
		| "/practice/cases/nominative/adjective"
		| "/practice/cases/nominative/article"
		| "/practice/cases/nominative/noun"
		| "/practice/cases/nominative/phrase"
		| "/practice/cases/review/adjectives"
		| "/practice/cases/review/articles"
		| "/practice/cases/review/nouns"
		| "/practice/cases/review/phrases"
		| "/practice/verbs/past/aorist-conjugation"
		| "/practice/verbs/past/aorist-formation"
		| "/practice/verbs/past/aorist-stems"
		| "/practice/verbs/past/eimai-past"
		| "/practice/verbs/present/eimai-present"
		| "/practice/verbs/present/present"
		| "/practice/verbs/present/present-irregular";
	id:
		| "__root__"
		| "/"
		| "/login"
		| "/progress"
		| "/register"
		| "/search"
		| "/support"
		| "/try"
		| "/api/errors"
		| "/api/milestones"
		| "/learn/nouns"
		| "/learn/verbs"
		| "/practice/_layout"
		| "/reference/$tab"
		| "/learn/"
		| "/practice/"
		| "/reference/"
		| "/api/push/log-tap"
		| "/api/push/snooze"
		| "/api/push/subscribe"
		| "/api/push/unsubscribe"
		| "/api/push/vapid-key"
		| "/api/webauthn/auth-options"
		| "/api/webauthn/auth-verify"
		| "/api/webauthn/register-options"
		| "/api/webauthn/register-verify"
		| "/learn/conversations/$tab"
		| "/learn/essentials/$subtab"
		| "/learn/phrases/$tab"
		| "/learn/verbs/$verbId"
		| "/practice/blocks/chunks"
		| "/practice/blocks/days-of-week"
		| "/practice/blocks/numbers"
		| "/practice/pronouns/object"
		| "/practice/pronouns/placement"
		| "/practice/pronouns/possessives"
		| "/practice/verbs/conjugation-endings"
		| "/practice/verbs/future-conjugation"
		| "/practice/verbs/imperatives"
		| "/practice/verbs/na-constructions"
		| "/learn/conversations/"
		| "/learn/essentials/"
		| "/learn/phrases/"
		| "/practice/blocks/"
		| "/practice/cases/"
		| "/practice/pronouns/"
		| "/practice/verbs/"
		| "/practice/cases/accusative/adjective"
		| "/practice/cases/accusative/article"
		| "/practice/cases/accusative/noun"
		| "/practice/cases/accusative/phrase"
		| "/practice/cases/genitive/adjective"
		| "/practice/cases/genitive/article"
		| "/practice/cases/genitive/noun"
		| "/practice/cases/genitive/phrase"
		| "/practice/cases/nominative/adjective"
		| "/practice/cases/nominative/article"
		| "/practice/cases/nominative/noun"
		| "/practice/cases/nominative/phrase"
		| "/practice/cases/review/adjectives"
		| "/practice/cases/review/articles"
		| "/practice/cases/review/nouns"
		| "/practice/cases/review/phrases"
		| "/practice/verbs/past/aorist-conjugation"
		| "/practice/verbs/past/aorist-formation"
		| "/practice/verbs/past/aorist-stems"
		| "/practice/verbs/past/eimai-past"
		| "/practice/verbs/present/eimai-present"
		| "/practice/verbs/present/present"
		| "/practice/verbs/present/present-irregular";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	LoginRoute: typeof LoginRoute;
	ProgressRoute: typeof ProgressRoute;
	RegisterRoute: typeof RegisterRoute;
	SearchRoute: typeof SearchRoute;
	SupportRoute: typeof SupportRoute;
	TryRoute: typeof TryRoute;
	ApiErrorsRoute: typeof ApiErrorsRoute;
	ApiMilestonesRoute: typeof ApiMilestonesRoute;
	LearnNounsRoute: typeof LearnNounsRoute;
	LearnVerbsRoute: typeof LearnVerbsRouteWithChildren;
	PracticeLayoutRoute: typeof PracticeLayoutRoute;
	ReferenceTabRoute: typeof ReferenceTabRoute;
	LearnIndexRoute: typeof LearnIndexRoute;
	PracticeIndexRoute: typeof PracticeIndexRoute;
	ReferenceIndexRoute: typeof ReferenceIndexRoute;
	ApiPushLogTapRoute: typeof ApiPushLogTapRoute;
	ApiPushSnoozeRoute: typeof ApiPushSnoozeRoute;
	ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute;
	ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute;
	ApiPushVapidKeyRoute: typeof ApiPushVapidKeyRoute;
	ApiWebauthnAuthOptionsRoute: typeof ApiWebauthnAuthOptionsRoute;
	ApiWebauthnAuthVerifyRoute: typeof ApiWebauthnAuthVerifyRoute;
	ApiWebauthnRegisterOptionsRoute: typeof ApiWebauthnRegisterOptionsRoute;
	ApiWebauthnRegisterVerifyRoute: typeof ApiWebauthnRegisterVerifyRoute;
	LearnConversationsTabRoute: typeof LearnConversationsTabRoute;
	LearnPhrasesTabRoute: typeof LearnPhrasesTabRoute;
	PracticeBlocksChunksRoute: typeof PracticeBlocksChunksRoute;
	PracticeBlocksDaysOfWeekRoute: typeof PracticeBlocksDaysOfWeekRoute;
	PracticeBlocksNumbersRoute: typeof PracticeBlocksNumbersRoute;
	PracticePronounsObjectRoute: typeof PracticePronounsObjectRoute;
	PracticePronounsPlacementRoute: typeof PracticePronounsPlacementRoute;
	PracticePronounsPossessivesRoute: typeof PracticePronounsPossessivesRoute;
	PracticeVerbsConjugationEndingsRoute: typeof PracticeVerbsConjugationEndingsRoute;
	PracticeVerbsFutureConjugationRoute: typeof PracticeVerbsFutureConjugationRoute;
	PracticeVerbsImperativesRoute: typeof PracticeVerbsImperativesRoute;
	PracticeVerbsNaConstructionsRoute: typeof PracticeVerbsNaConstructionsRoute;
	LearnPhrasesIndexRoute: typeof LearnPhrasesIndexRoute;
	PracticeBlocksIndexRoute: typeof PracticeBlocksIndexRoute;
	PracticeCasesIndexRoute: typeof PracticeCasesIndexRoute;
	PracticePronounsIndexRoute: typeof PracticePronounsIndexRoute;
	PracticeVerbsIndexRoute: typeof PracticeVerbsIndexRoute;
	PracticeCasesAccusativeAdjectiveRoute: typeof PracticeCasesAccusativeAdjectiveRoute;
	PracticeCasesAccusativeArticleRoute: typeof PracticeCasesAccusativeArticleRoute;
	PracticeCasesAccusativeNounRoute: typeof PracticeCasesAccusativeNounRoute;
	PracticeCasesAccusativePhraseRoute: typeof PracticeCasesAccusativePhraseRoute;
	PracticeCasesGenitiveAdjectiveRoute: typeof PracticeCasesGenitiveAdjectiveRoute;
	PracticeCasesGenitiveArticleRoute: typeof PracticeCasesGenitiveArticleRoute;
	PracticeCasesGenitiveNounRoute: typeof PracticeCasesGenitiveNounRoute;
	PracticeCasesGenitivePhraseRoute: typeof PracticeCasesGenitivePhraseRoute;
	PracticeCasesNominativeAdjectiveRoute: typeof PracticeCasesNominativeAdjectiveRoute;
	PracticeCasesNominativeArticleRoute: typeof PracticeCasesNominativeArticleRoute;
	PracticeCasesNominativeNounRoute: typeof PracticeCasesNominativeNounRoute;
	PracticeCasesNominativePhraseRoute: typeof PracticeCasesNominativePhraseRoute;
	PracticeCasesReviewAdjectivesRoute: typeof PracticeCasesReviewAdjectivesRoute;
	PracticeCasesReviewArticlesRoute: typeof PracticeCasesReviewArticlesRoute;
	PracticeCasesReviewNounsRoute: typeof PracticeCasesReviewNounsRoute;
	PracticeCasesReviewPhrasesRoute: typeof PracticeCasesReviewPhrasesRoute;
	PracticeVerbsPastAoristConjugationRoute: typeof PracticeVerbsPastAoristConjugationRoute;
	PracticeVerbsPastAoristFormationRoute: typeof PracticeVerbsPastAoristFormationRoute;
	PracticeVerbsPastAoristStemsRoute: typeof PracticeVerbsPastAoristStemsRoute;
	PracticeVerbsPastEimaiPastRoute: typeof PracticeVerbsPastEimaiPastRoute;
	PracticeVerbsPresentEimaiPresentRoute: typeof PracticeVerbsPresentEimaiPresentRoute;
	PracticeVerbsPresentPresentRoute: typeof PracticeVerbsPresentPresentRoute;
	PracticeVerbsPresentPresentIrregularRoute: typeof PracticeVerbsPresentPresentIrregularRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/try": {
			id: "/try";
			path: "/try";
			fullPath: "/try";
			preLoaderRoute: typeof TryRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/support": {
			id: "/support";
			path: "/support";
			fullPath: "/support";
			preLoaderRoute: typeof SupportRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/search": {
			id: "/search";
			path: "/search";
			fullPath: "/search";
			preLoaderRoute: typeof SearchRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/register": {
			id: "/register";
			path: "/register";
			fullPath: "/register";
			preLoaderRoute: typeof RegisterRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/progress": {
			id: "/progress";
			path: "/progress";
			fullPath: "/progress";
			preLoaderRoute: typeof ProgressRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/reference/": {
			id: "/reference/";
			path: "/reference";
			fullPath: "/reference/";
			preLoaderRoute: typeof ReferenceIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/": {
			id: "/practice/";
			path: "/practice";
			fullPath: "/practice/";
			preLoaderRoute: typeof PracticeIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/learn/": {
			id: "/learn/";
			path: "/learn";
			fullPath: "/learn/";
			preLoaderRoute: typeof LearnIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/reference/$tab": {
			id: "/reference/$tab";
			path: "/reference/$tab";
			fullPath: "/reference/$tab";
			preLoaderRoute: typeof ReferenceTabRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/_layout": {
			id: "/practice/_layout";
			path: "/practice";
			fullPath: "/practice";
			preLoaderRoute: typeof PracticeLayoutRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/learn/verbs": {
			id: "/learn/verbs";
			path: "/learn/verbs";
			fullPath: "/learn/verbs";
			preLoaderRoute: typeof LearnVerbsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/learn/nouns": {
			id: "/learn/nouns";
			path: "/learn/nouns";
			fullPath: "/learn/nouns";
			preLoaderRoute: typeof LearnNounsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/milestones": {
			id: "/api/milestones";
			path: "/api/milestones";
			fullPath: "/api/milestones";
			preLoaderRoute: typeof ApiMilestonesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/errors": {
			id: "/api/errors";
			path: "/api/errors";
			fullPath: "/api/errors";
			preLoaderRoute: typeof ApiErrorsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/": {
			id: "/practice/verbs/";
			path: "/practice/verbs";
			fullPath: "/practice/verbs/";
			preLoaderRoute: typeof PracticeVerbsIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/pronouns/": {
			id: "/practice/pronouns/";
			path: "/practice/pronouns";
			fullPath: "/practice/pronouns/";
			preLoaderRoute: typeof PracticePronounsIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/": {
			id: "/practice/cases/";
			path: "/practice/cases";
			fullPath: "/practice/cases/";
			preLoaderRoute: typeof PracticeCasesIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/blocks/": {
			id: "/practice/blocks/";
			path: "/practice/blocks";
			fullPath: "/practice/blocks/";
			preLoaderRoute: typeof PracticeBlocksIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/learn/phrases/": {
			id: "/learn/phrases/";
			path: "/learn/phrases";
			fullPath: "/learn/phrases/";
			preLoaderRoute: typeof LearnPhrasesIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/learn/essentials/": {
			id: "/learn/essentials/";
			path: "/";
			fullPath: "/learn/essentials/";
			preLoaderRoute: typeof LearnEssentialsIndexRouteImport;
			parentRoute: typeof LearnEssentialsRouteRoute;
		};
		"/learn/conversations/": {
			id: "/learn/conversations/";
			path: "/";
			fullPath: "/learn/conversations/";
			preLoaderRoute: typeof LearnConversationsIndexRouteImport;
			parentRoute: typeof LearnConversationsRouteRoute;
		};
		"/practice/verbs/na-constructions": {
			id: "/practice/verbs/na-constructions";
			path: "/practice/verbs/na-constructions";
			fullPath: "/practice/verbs/na-constructions";
			preLoaderRoute: typeof PracticeVerbsNaConstructionsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/imperatives": {
			id: "/practice/verbs/imperatives";
			path: "/practice/verbs/imperatives";
			fullPath: "/practice/verbs/imperatives";
			preLoaderRoute: typeof PracticeVerbsImperativesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/future-conjugation": {
			id: "/practice/verbs/future-conjugation";
			path: "/practice/verbs/future-conjugation";
			fullPath: "/practice/verbs/future-conjugation";
			preLoaderRoute: typeof PracticeVerbsFutureConjugationRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/conjugation-endings": {
			id: "/practice/verbs/conjugation-endings";
			path: "/practice/verbs/conjugation-endings";
			fullPath: "/practice/verbs/conjugation-endings";
			preLoaderRoute: typeof PracticeVerbsConjugationEndingsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/pronouns/possessives": {
			id: "/practice/pronouns/possessives";
			path: "/practice/pronouns/possessives";
			fullPath: "/practice/pronouns/possessives";
			preLoaderRoute: typeof PracticePronounsPossessivesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/pronouns/placement": {
			id: "/practice/pronouns/placement";
			path: "/practice/pronouns/placement";
			fullPath: "/practice/pronouns/placement";
			preLoaderRoute: typeof PracticePronounsPlacementRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/pronouns/object": {
			id: "/practice/pronouns/object";
			path: "/practice/pronouns/object";
			fullPath: "/practice/pronouns/object";
			preLoaderRoute: typeof PracticePronounsObjectRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/blocks/numbers": {
			id: "/practice/blocks/numbers";
			path: "/practice/blocks/numbers";
			fullPath: "/practice/blocks/numbers";
			preLoaderRoute: typeof PracticeBlocksNumbersRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/blocks/days-of-week": {
			id: "/practice/blocks/days-of-week";
			path: "/practice/blocks/days-of-week";
			fullPath: "/practice/blocks/days-of-week";
			preLoaderRoute: typeof PracticeBlocksDaysOfWeekRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/blocks/chunks": {
			id: "/practice/blocks/chunks";
			path: "/practice/blocks/chunks";
			fullPath: "/practice/blocks/chunks";
			preLoaderRoute: typeof PracticeBlocksChunksRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/learn/verbs/$verbId": {
			id: "/learn/verbs/$verbId";
			path: "/$verbId";
			fullPath: "/learn/verbs/$verbId";
			preLoaderRoute: typeof LearnVerbsVerbIdRouteImport;
			parentRoute: typeof LearnVerbsRoute;
		};
		"/learn/phrases/$tab": {
			id: "/learn/phrases/$tab";
			path: "/learn/phrases/$tab";
			fullPath: "/learn/phrases/$tab";
			preLoaderRoute: typeof LearnPhrasesTabRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/learn/essentials/$subtab": {
			id: "/learn/essentials/$subtab";
			path: "/$subtab";
			fullPath: "/learn/essentials/$subtab";
			preLoaderRoute: typeof LearnEssentialsSubtabRouteImport;
			parentRoute: typeof LearnEssentialsRouteRoute;
		};
		"/learn/conversations/$tab": {
			id: "/learn/conversations/$tab";
			path: "/learn/conversations/$tab";
			fullPath: "/learn/conversations/$tab";
			preLoaderRoute: typeof LearnConversationsTabRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/webauthn/register-verify": {
			id: "/api/webauthn/register-verify";
			path: "/api/webauthn/register-verify";
			fullPath: "/api/webauthn/register-verify";
			preLoaderRoute: typeof ApiWebauthnRegisterVerifyRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/webauthn/register-options": {
			id: "/api/webauthn/register-options";
			path: "/api/webauthn/register-options";
			fullPath: "/api/webauthn/register-options";
			preLoaderRoute: typeof ApiWebauthnRegisterOptionsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/webauthn/auth-verify": {
			id: "/api/webauthn/auth-verify";
			path: "/api/webauthn/auth-verify";
			fullPath: "/api/webauthn/auth-verify";
			preLoaderRoute: typeof ApiWebauthnAuthVerifyRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/webauthn/auth-options": {
			id: "/api/webauthn/auth-options";
			path: "/api/webauthn/auth-options";
			fullPath: "/api/webauthn/auth-options";
			preLoaderRoute: typeof ApiWebauthnAuthOptionsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/push/vapid-key": {
			id: "/api/push/vapid-key";
			path: "/api/push/vapid-key";
			fullPath: "/api/push/vapid-key";
			preLoaderRoute: typeof ApiPushVapidKeyRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/push/unsubscribe": {
			id: "/api/push/unsubscribe";
			path: "/api/push/unsubscribe";
			fullPath: "/api/push/unsubscribe";
			preLoaderRoute: typeof ApiPushUnsubscribeRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/push/subscribe": {
			id: "/api/push/subscribe";
			path: "/api/push/subscribe";
			fullPath: "/api/push/subscribe";
			preLoaderRoute: typeof ApiPushSubscribeRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/push/snooze": {
			id: "/api/push/snooze";
			path: "/api/push/snooze";
			fullPath: "/api/push/snooze";
			preLoaderRoute: typeof ApiPushSnoozeRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/push/log-tap": {
			id: "/api/push/log-tap";
			path: "/api/push/log-tap";
			fullPath: "/api/push/log-tap";
			preLoaderRoute: typeof ApiPushLogTapRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/present/present-irregular": {
			id: "/practice/verbs/present/present-irregular";
			path: "/practice/verbs/present/present-irregular";
			fullPath: "/practice/verbs/present/present-irregular";
			preLoaderRoute: typeof PracticeVerbsPresentPresentIrregularRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/present/present": {
			id: "/practice/verbs/present/present";
			path: "/practice/verbs/present/present";
			fullPath: "/practice/verbs/present/present";
			preLoaderRoute: typeof PracticeVerbsPresentPresentRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/present/eimai-present": {
			id: "/practice/verbs/present/eimai-present";
			path: "/practice/verbs/present/eimai-present";
			fullPath: "/practice/verbs/present/eimai-present";
			preLoaderRoute: typeof PracticeVerbsPresentEimaiPresentRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/past/eimai-past": {
			id: "/practice/verbs/past/eimai-past";
			path: "/practice/verbs/past/eimai-past";
			fullPath: "/practice/verbs/past/eimai-past";
			preLoaderRoute: typeof PracticeVerbsPastEimaiPastRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/past/aorist-stems": {
			id: "/practice/verbs/past/aorist-stems";
			path: "/practice/verbs/past/aorist-stems";
			fullPath: "/practice/verbs/past/aorist-stems";
			preLoaderRoute: typeof PracticeVerbsPastAoristStemsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/past/aorist-formation": {
			id: "/practice/verbs/past/aorist-formation";
			path: "/practice/verbs/past/aorist-formation";
			fullPath: "/practice/verbs/past/aorist-formation";
			preLoaderRoute: typeof PracticeVerbsPastAoristFormationRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/verbs/past/aorist-conjugation": {
			id: "/practice/verbs/past/aorist-conjugation";
			path: "/practice/verbs/past/aorist-conjugation";
			fullPath: "/practice/verbs/past/aorist-conjugation";
			preLoaderRoute: typeof PracticeVerbsPastAoristConjugationRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/review/phrases": {
			id: "/practice/cases/review/phrases";
			path: "/practice/cases/review/phrases";
			fullPath: "/practice/cases/review/phrases";
			preLoaderRoute: typeof PracticeCasesReviewPhrasesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/review/nouns": {
			id: "/practice/cases/review/nouns";
			path: "/practice/cases/review/nouns";
			fullPath: "/practice/cases/review/nouns";
			preLoaderRoute: typeof PracticeCasesReviewNounsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/review/articles": {
			id: "/practice/cases/review/articles";
			path: "/practice/cases/review/articles";
			fullPath: "/practice/cases/review/articles";
			preLoaderRoute: typeof PracticeCasesReviewArticlesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/review/adjectives": {
			id: "/practice/cases/review/adjectives";
			path: "/practice/cases/review/adjectives";
			fullPath: "/practice/cases/review/adjectives";
			preLoaderRoute: typeof PracticeCasesReviewAdjectivesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/nominative/phrase": {
			id: "/practice/cases/nominative/phrase";
			path: "/practice/cases/nominative/phrase";
			fullPath: "/practice/cases/nominative/phrase";
			preLoaderRoute: typeof PracticeCasesNominativePhraseRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/nominative/noun": {
			id: "/practice/cases/nominative/noun";
			path: "/practice/cases/nominative/noun";
			fullPath: "/practice/cases/nominative/noun";
			preLoaderRoute: typeof PracticeCasesNominativeNounRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/nominative/article": {
			id: "/practice/cases/nominative/article";
			path: "/practice/cases/nominative/article";
			fullPath: "/practice/cases/nominative/article";
			preLoaderRoute: typeof PracticeCasesNominativeArticleRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/nominative/adjective": {
			id: "/practice/cases/nominative/adjective";
			path: "/practice/cases/nominative/adjective";
			fullPath: "/practice/cases/nominative/adjective";
			preLoaderRoute: typeof PracticeCasesNominativeAdjectiveRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/genitive/phrase": {
			id: "/practice/cases/genitive/phrase";
			path: "/practice/cases/genitive/phrase";
			fullPath: "/practice/cases/genitive/phrase";
			preLoaderRoute: typeof PracticeCasesGenitivePhraseRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/genitive/noun": {
			id: "/practice/cases/genitive/noun";
			path: "/practice/cases/genitive/noun";
			fullPath: "/practice/cases/genitive/noun";
			preLoaderRoute: typeof PracticeCasesGenitiveNounRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/genitive/article": {
			id: "/practice/cases/genitive/article";
			path: "/practice/cases/genitive/article";
			fullPath: "/practice/cases/genitive/article";
			preLoaderRoute: typeof PracticeCasesGenitiveArticleRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/genitive/adjective": {
			id: "/practice/cases/genitive/adjective";
			path: "/practice/cases/genitive/adjective";
			fullPath: "/practice/cases/genitive/adjective";
			preLoaderRoute: typeof PracticeCasesGenitiveAdjectiveRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/accusative/phrase": {
			id: "/practice/cases/accusative/phrase";
			path: "/practice/cases/accusative/phrase";
			fullPath: "/practice/cases/accusative/phrase";
			preLoaderRoute: typeof PracticeCasesAccusativePhraseRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/accusative/noun": {
			id: "/practice/cases/accusative/noun";
			path: "/practice/cases/accusative/noun";
			fullPath: "/practice/cases/accusative/noun";
			preLoaderRoute: typeof PracticeCasesAccusativeNounRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/accusative/article": {
			id: "/practice/cases/accusative/article";
			path: "/practice/cases/accusative/article";
			fullPath: "/practice/cases/accusative/article";
			preLoaderRoute: typeof PracticeCasesAccusativeArticleRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/practice/cases/accusative/adjective": {
			id: "/practice/cases/accusative/adjective";
			path: "/practice/cases/accusative/adjective";
			fullPath: "/practice/cases/accusative/adjective";
			preLoaderRoute: typeof PracticeCasesAccusativeAdjectiveRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

interface LearnVerbsRouteChildren {
	LearnVerbsVerbIdRoute: typeof LearnVerbsVerbIdRoute;
}

const LearnVerbsRouteChildren: LearnVerbsRouteChildren = {
	LearnVerbsVerbIdRoute: LearnVerbsVerbIdRoute,
};

const LearnVerbsRouteWithChildren = LearnVerbsRoute._addFileChildren(LearnVerbsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	LoginRoute: LoginRoute,
	ProgressRoute: ProgressRoute,
	RegisterRoute: RegisterRoute,
	SearchRoute: SearchRoute,
	SupportRoute: SupportRoute,
	TryRoute: TryRoute,
	ApiErrorsRoute: ApiErrorsRoute,
	ApiMilestonesRoute: ApiMilestonesRoute,
	LearnNounsRoute: LearnNounsRoute,
	LearnVerbsRoute: LearnVerbsRouteWithChildren,
	PracticeLayoutRoute: PracticeLayoutRoute,
	ReferenceTabRoute: ReferenceTabRoute,
	LearnIndexRoute: LearnIndexRoute,
	PracticeIndexRoute: PracticeIndexRoute,
	ReferenceIndexRoute: ReferenceIndexRoute,
	ApiPushLogTapRoute: ApiPushLogTapRoute,
	ApiPushSnoozeRoute: ApiPushSnoozeRoute,
	ApiPushSubscribeRoute: ApiPushSubscribeRoute,
	ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
	ApiPushVapidKeyRoute: ApiPushVapidKeyRoute,
	ApiWebauthnAuthOptionsRoute: ApiWebauthnAuthOptionsRoute,
	ApiWebauthnAuthVerifyRoute: ApiWebauthnAuthVerifyRoute,
	ApiWebauthnRegisterOptionsRoute: ApiWebauthnRegisterOptionsRoute,
	ApiWebauthnRegisterVerifyRoute: ApiWebauthnRegisterVerifyRoute,
	LearnConversationsTabRoute: LearnConversationsTabRoute,
	LearnPhrasesTabRoute: LearnPhrasesTabRoute,
	PracticeBlocksChunksRoute: PracticeBlocksChunksRoute,
	PracticeBlocksDaysOfWeekRoute: PracticeBlocksDaysOfWeekRoute,
	PracticeBlocksNumbersRoute: PracticeBlocksNumbersRoute,
	PracticePronounsObjectRoute: PracticePronounsObjectRoute,
	PracticePronounsPlacementRoute: PracticePronounsPlacementRoute,
	PracticePronounsPossessivesRoute: PracticePronounsPossessivesRoute,
	PracticeVerbsConjugationEndingsRoute: PracticeVerbsConjugationEndingsRoute,
	PracticeVerbsFutureConjugationRoute: PracticeVerbsFutureConjugationRoute,
	PracticeVerbsImperativesRoute: PracticeVerbsImperativesRoute,
	PracticeVerbsNaConstructionsRoute: PracticeVerbsNaConstructionsRoute,
	LearnPhrasesIndexRoute: LearnPhrasesIndexRoute,
	PracticeBlocksIndexRoute: PracticeBlocksIndexRoute,
	PracticeCasesIndexRoute: PracticeCasesIndexRoute,
	PracticePronounsIndexRoute: PracticePronounsIndexRoute,
	PracticeVerbsIndexRoute: PracticeVerbsIndexRoute,
	PracticeCasesAccusativeAdjectiveRoute: PracticeCasesAccusativeAdjectiveRoute,
	PracticeCasesAccusativeArticleRoute: PracticeCasesAccusativeArticleRoute,
	PracticeCasesAccusativeNounRoute: PracticeCasesAccusativeNounRoute,
	PracticeCasesAccusativePhraseRoute: PracticeCasesAccusativePhraseRoute,
	PracticeCasesGenitiveAdjectiveRoute: PracticeCasesGenitiveAdjectiveRoute,
	PracticeCasesGenitiveArticleRoute: PracticeCasesGenitiveArticleRoute,
	PracticeCasesGenitiveNounRoute: PracticeCasesGenitiveNounRoute,
	PracticeCasesGenitivePhraseRoute: PracticeCasesGenitivePhraseRoute,
	PracticeCasesNominativeAdjectiveRoute: PracticeCasesNominativeAdjectiveRoute,
	PracticeCasesNominativeArticleRoute: PracticeCasesNominativeArticleRoute,
	PracticeCasesNominativeNounRoute: PracticeCasesNominativeNounRoute,
	PracticeCasesNominativePhraseRoute: PracticeCasesNominativePhraseRoute,
	PracticeCasesReviewAdjectivesRoute: PracticeCasesReviewAdjectivesRoute,
	PracticeCasesReviewArticlesRoute: PracticeCasesReviewArticlesRoute,
	PracticeCasesReviewNounsRoute: PracticeCasesReviewNounsRoute,
	PracticeCasesReviewPhrasesRoute: PracticeCasesReviewPhrasesRoute,
	PracticeVerbsPastAoristConjugationRoute: PracticeVerbsPastAoristConjugationRoute,
	PracticeVerbsPastAoristFormationRoute: PracticeVerbsPastAoristFormationRoute,
	PracticeVerbsPastAoristStemsRoute: PracticeVerbsPastAoristStemsRoute,
	PracticeVerbsPastEimaiPastRoute: PracticeVerbsPastEimaiPastRoute,
	PracticeVerbsPresentEimaiPresentRoute: PracticeVerbsPresentEimaiPresentRoute,
	PracticeVerbsPresentPresentRoute: PracticeVerbsPresentPresentRoute,
	PracticeVerbsPresentPresentIrregularRoute: PracticeVerbsPresentPresentIrregularRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
